/**
 * Session Data Ingestion Pipeline for Johnny5 Session Memory
 *
 * When a checkpoint is created in the IDE, this module extracts meaningful
 * chunks from the session data and indexes them into the `memory_chunks` table.
 *
 * Source types produced:
 * - ide_session_summary: AI-generated or inferred session summary
 * - ide_terminal_chunk: Terminal output grouped by command
 * - ide_file_change: Files modified during session
 * - ide_error: Errors with surrounding context
 * - ide_git_commit: Git commits during session
 * - ide_command: Commands executed
 *
 * Source ID format: ide:{sessionId}:{chunkType}:{index}
 */

import { randomUUID } from 'crypto';
import {
  upsertMemoryChunk,
  generateContentHash,
  getDb,
} from '@/lib/johnny5-db';

// ============================================================================
// Constants
// ============================================================================

const MAX_TERMINAL_CHUNKS = 20;
const MAX_ERROR_CHUNKS = 10;
const MAX_CHUNKS_PER_SESSION = 50;
const MAX_TOKENS_PER_CHUNK = 500;
const MIN_TERMINAL_LENGTH = 200;

// ============================================================================
// ANSI Code Stripping
// ============================================================================

/**
 * Strip ANSI escape codes from terminal output before indexing.
 * Handles: CSI sequences (colors, cursor), private CSI (?25h),
 * OSC sequences (window titles), and character set selections.
 */
function stripAnsiCodes(text: string): string {
  return text
    .replace(/\x1b\[[0-9;]*[a-zA-Z]/g, '')        // CSI: colors, cursor movement
    .replace(/\x1b\[\?[0-9;]*[a-zA-Z]/g, '')       // Private CSI: ?25h, ?2004h
    .replace(/\x1b\[[<>=]?[0-9;]*[a-zA-Z~]/g, '')  // Extended CSI: mouse, keypad mode
    .replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g, '') // OSC: window titles
    .replace(/\x1b\([A-Z]/g, '')                     // Character set selection
    .replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g, '') // Control chars (^H, ^G, etc.) except \t \n \r
    .replace(/\r(?!\n)/g, '')                        // Carriage returns (not \r\n)
    .replace(/\^H/g, '')                             // Literal ^H (backspace display)
    .replace(/\^\[\[<[a-z]/g, '');                   // Literal ^[[<u style sequences
}

/**
 * Extract file paths from snapshot files data.
 * Handles JSON-stringified IDEFile[] arrays and plain objects.
 */
function extractFilePathsFromSnapshot(files: any): string[] {
  if (!files) return [];
  try {
    const parsed = typeof files === 'string' ? JSON.parse(files) : files;
    if (Array.isArray(parsed)) {
      return parsed
        .map((f: any) => (typeof f === 'string' ? f : f.path || f.name || ''))
        .filter(Boolean);
    }
    if (typeof parsed === 'object') {
      return Object.keys(parsed);
    }
  } catch {}
  return [];
}

// ============================================================================
// Types
// ============================================================================

/**
 * Checkpoint data structure passed from the IDE when a checkpoint is created.
 */
export interface CheckpointData {
  id: string;
  sessionId: string;
  name?: string;
  description?: string;
  timestamp: string;
  terminalHistory?: string;
  openFiles?: string[];
  gitBranch?: string;
  autoGenerated?: boolean;
  data?: {
    activeFile?: string;
    snapshot?: {
      files?: Record<string, any>;
      projectPath?: string;
    };
    conversationHistory?: Array<{ role: string; content: string }>;
  };
}

/** A chunk extracted from terminal history. */
interface TerminalChunk {
  content: string;
  heading: string;
  sectionType: 'terminal_command' | 'terminal_error' | 'terminal_output';
}

/** A chunk extracted from error detection. */
interface ErrorChunk {
  content: string;
  heading: string;
}

// ============================================================================
// Concurrent Indexing Protection
// ============================================================================

const indexingLocks = new Set<string>();

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Estimate token count from text length.
 * Uses the standard ~4 characters per token heuristic.
 *
 * @param text - The text to estimate tokens for
 * @returns Estimated token count
 */
function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

/**
 * Redact sensitive data from content before indexing.
 * Removes API keys, tokens, secrets, passwords, and environment variable values.
 *
 * @param content - Raw content that may contain sensitive data
 * @returns Content with sensitive values replaced by [REDACTED]
 */
export function redactSensitiveData(content: string): string {
  let redacted = content;

  // API keys, tokens, secrets, passwords in key=value or key: value patterns
  redacted = redacted.replace(
    /(?:api[_-]?key|token|secret|password)\s*[:=]\s*['"]?[\w\-\.]+/gi,
    (match) => {
      const sepIndex = match.search(/[:=]/);
      const prefix = match.substring(0, sepIndex + 1);
      return `${prefix} [REDACTED]`;
    }
  );

  // Known environment variable prefixes with their values
  redacted = redacted.replace(
    /(ANTHROPIC|OPENAI|AWS|STRIPE|DATABASE|MONGODB|REDIS|MYSQL|POSTGRES)_[A-Z_]+=\S+/g,
    '[REDACTED]'
  );

  return redacted;
}

/**
 * Truncate a chunk to the maximum token limit.
 * Keeps the first and last portions with a truncation marker in between.
 *
 * @param text - Text to potentially truncate
 * @returns Truncated text if over limit, original text otherwise
 */
function truncateChunk(text: string): string {
  const tokens = estimateTokens(text);
  if (tokens <= MAX_TOKENS_PER_CHUNK) {
    return text;
  }

  // Keep first 200 tokens (~800 chars) and last 200 tokens (~800 chars)
  const keepChars = 200 * 4;
  const first = text.substring(0, keepChars);
  const last = text.substring(text.length - keepChars);
  return `${first}\n... [output truncated] ...\n${last}`;
}

/**
 * Build a source ID for a chunk following the ide:{sessionId}:{chunkType}:{index} format.
 *
 * @param sessionId - The session identifier
 * @param chunkType - The type of chunk (e.g., 'terminal', 'error', 'file', 'summary')
 * @param index - The chunk index within its type
 * @returns Formatted source ID
 */
function buildSourceId(sessionId: string, chunkType: string, index: number): string {
  return `ide:${sessionId}:${chunkType}:${index}`;
}

/**
 * Extract the project name from a full project path.
 *
 * @param projectPath - Full filesystem path to the project
 * @returns The last directory component as the project name
 */
function getProjectName(projectPath: string): string {
  const parts = projectPath.replace(/\/+$/, '').split('/');
  return parts[parts.length - 1] || 'unknown';
}

// ============================================================================
// Command Detection
// ============================================================================

/** Regex patterns for recognizing shell commands at the start of a line. */
const COMMAND_PREFIXES = /^(?:\$\s+)?(?:npm|npx|git|node|python|python3|cd|ls|mkdir|cat|echo|rm|cp|mv|touch|curl|wget|docker|make|cargo|go|pip|yarn|pnpm|brew|apt|sudo|chmod|chown)\b/;

/** Patterns indicating only navigation/noise commands. */
const NAVIGATION_ONLY_COMMANDS = /^(?:\$\s+)?(?:cd|ls|pwd|clear|cls)\b/;

// ============================================================================
// Terminal Chunking
// ============================================================================

/**
 * Split terminal history into meaningful chunks grouped by command boundaries.
 *
 * Each command and its following output are grouped into a single chunk.
 * Chunks are classified as command, error, or general output.
 * Noise (very short, whitespace-only) is filtered out.
 *
 * @param terminalHistory - Raw terminal history string
 * @returns Array of extracted terminal chunks, capped at MAX_TERMINAL_CHUNKS
 */
function chunkTerminalHistory(terminalHistory: string): TerminalChunk[] {
  if (!terminalHistory || terminalHistory.trim().length === 0) {
    return [];
  }

  // Split by double-newline boundaries (blank lines)
  const blocks = terminalHistory.split(/\n\s*\n/).filter((b) => b.trim().length > 0);

  const chunks: TerminalChunk[] = [];
  let currentCommand: string | null = null;
  let currentOutput: string[] = [];

  const flushCurrent = () => {
    if (currentCommand === null && currentOutput.length === 0) {
      return;
    }

    const combined = currentCommand
      ? [currentCommand, ...currentOutput].join('\n\n')
      : currentOutput.join('\n\n');

    const trimmed = combined.trim();

    // Skip noise: too short or whitespace-only
    if (trimmed.length < 10) {
      currentCommand = null;
      currentOutput = [];
      return;
    }

    const truncated = truncateChunk(trimmed);
    const firstLine = trimmed.split('\n')[0].substring(0, 100);

    // Classify the chunk
    let sectionType: TerminalChunk['sectionType'] = 'terminal_output';
    if (currentCommand) {
      sectionType = 'terminal_command';
    }
    if (/Error:|ERR!|FAIL|TypeError|ReferenceError|SyntaxError/i.test(trimmed)) {
      sectionType = 'terminal_error';
    }

    chunks.push({
      content: truncated,
      heading: firstLine,
      sectionType,
    });

    currentCommand = null;
    currentOutput = [];
  };

  for (const block of blocks) {
    const firstLine = block.trim().split('\n')[0];

    if (COMMAND_PREFIXES.test(firstLine)) {
      // This block starts with a command - flush previous and start new group
      flushCurrent();
      currentCommand = block.trim();
    } else {
      // This is output - attach to current command group
      currentOutput.push(block.trim());
    }
  }

  // Flush the last group
  flushCurrent();

  return chunks.slice(0, MAX_TERMINAL_CHUNKS);
}

// ============================================================================
// Error Extraction
// ============================================================================

/**
 * Extract error chunks from terminal history with surrounding context.
 *
 * Scans for common error patterns and captures 5 lines of context
 * before and after each error occurrence.
 *
 * @param terminalHistory - Raw terminal history string
 * @returns Array of extracted error chunks, capped at MAX_ERROR_CHUNKS
 */
function extractErrors(terminalHistory: string): ErrorChunk[] {
  if (!terminalHistory || terminalHistory.trim().length === 0) {
    return [];
  }

  const lines = terminalHistory.split('\n');
  const errorPatterns = [
    /Error:/i,
    /ERR!/,
    /FAIL/i,
    /TypeError|ReferenceError|SyntaxError/,
    /at\s+\S+\s+\(.*:\d+:\d+\)/,
  ];

  const errorIndices: number[] = [];

  for (let i = 0; i < lines.length; i++) {
    for (const pattern of errorPatterns) {
      if (pattern.test(lines[i])) {
        errorIndices.push(i);
        break;
      }
    }
  }

  // Deduplicate overlapping ranges
  const chunks: ErrorChunk[] = [];
  const processedRanges = new Set<string>();

  for (const idx of errorIndices) {
    const start = Math.max(0, idx - 5);
    const end = Math.min(lines.length - 1, idx + 5);
    const rangeKey = `${start}-${end}`;

    if (processedRanges.has(rangeKey)) {
      continue;
    }
    processedRanges.add(rangeKey);

    const contextLines = lines.slice(start, end + 1);
    const content = contextLines.join('\n').trim();

    if (content.length < 10) {
      continue;
    }

    const heading = lines[idx].trim().substring(0, 100);

    chunks.push({
      content: truncateChunk(content),
      heading,
    });

    if (chunks.length >= MAX_ERROR_CHUNKS) {
      break;
    }
  }

  return chunks;
}

// ============================================================================
// Noise Filtering
// ============================================================================

/**
 * Determine whether a session should be skipped entirely based on noise heuristics.
 *
 * Sessions are considered noise when:
 * - Terminal history is very short AND there are no file changes or git activity
 * - Only navigation commands were executed (cd, ls, pwd, clear)
 * - Session duration is less than 2 minutes
 *
 * @param checkpoint - The checkpoint data to evaluate
 * @returns true if the session should be skipped
 */
function isNoiseSession(checkpoint: CheckpointData): boolean {
  const hasTerminal = !!checkpoint.terminalHistory && checkpoint.terminalHistory.trim().length >= MIN_TERMINAL_LENGTH;
  const hasFiles = !!checkpoint.openFiles && checkpoint.openFiles.length > 0;
  const hasGit = !!checkpoint.gitBranch;
  const hasSnapshot = !!checkpoint.data?.snapshot?.files && Object.keys(checkpoint.data.snapshot.files).length > 0;

  // No meaningful content at all
  if (!hasTerminal && !hasFiles && !hasGit && !hasSnapshot) {
    return true;
  }

  // Terminal too short and nothing else
  if (!hasTerminal && !hasFiles && !hasSnapshot) {
    return true;
  }

  // Only navigation commands
  if (checkpoint.terminalHistory) {
    const lines = checkpoint.terminalHistory.split('\n').filter((l) => l.trim().length > 0);
    const allNavigation = lines.every((line) => {
      const trimmed = line.trim();
      return trimmed.length === 0 || NAVIGATION_ONLY_COMMANDS.test(trimmed);
    });
    if (allNavigation && !hasFiles && !hasSnapshot) {
      return true;
    }
  }

  // Session too short (less than 2 minutes)
  try {
    const sessionStart = new Date(checkpoint.timestamp).getTime();
    const now = Date.now();
    const durationMs = now - sessionStart;
    if (durationMs < 2 * 60 * 1000 && !hasFiles && !hasSnapshot) {
      return true;
    }
  } catch {
    // Invalid timestamp - don't skip on this basis
  }

  return false;
}

// ============================================================================
// Main Export
// ============================================================================

/**
 * Index session data from a checkpoint into memory chunks for semantic search.
 *
 * This is the main entry point for the session data ingestion pipeline.
 * It extracts terminal chunks, file changes, errors, and a session summary
 * from the checkpoint data and upserts them into the `memory_chunks` table.
 *
 * Concurrent calls for the same session are protected by an in-memory lock.
 * Auto-generated checkpoints for already-indexed sessions are skipped.
 *
 * @param checkpoint - The checkpoint data from the IDE
 * @param sessionId - The session identifier
 * @param userId - The user identifier for the memory chunks
 * @returns Object with chunksIndexed and skipped counts
 *
 * @example
 * ```typescript
 * const result = await indexSessionFromCheckpoint(checkpoint, 'session_123', 'user_1');
 * console.log(`Indexed ${result.chunksIndexed} chunks, skipped ${result.skipped}`);
 * ```
 */
export async function indexSessionFromCheckpoint(
  checkpoint: CheckpointData,
  sessionId: string,
  userId: string
): Promise<{ chunksIndexed: number; skipped: number }> {
  // Concurrent indexing protection
  if (indexingLocks.has(sessionId)) {
    console.log(`[SessionIndexer] Session ${sessionId} is already being indexed, skipping`);
    return { chunksIndexed: 0, skipped: 0 };
  }

  indexingLocks.add(sessionId);

  try {
    // Check if session already indexed
    const database = getDb();
    const existingRow = database
      .prepare(`SELECT COUNT(*) as count FROM memory_chunks WHERE source_id LIKE ?`)
      .get(`ide:${sessionId}:%`) as { count: number } | undefined;

    const existingCount = existingRow?.count ?? 0;

    if (existingCount > 0 && checkpoint.autoGenerated) {
      console.log(
        `[SessionIndexer] Session ${sessionId} already indexed (${existingCount} chunks) and checkpoint is auto-generated, skipping`
      );
      return { chunksIndexed: 0, skipped: existingCount };
    }

    // Noise filtering
    if (isNoiseSession(checkpoint)) {
      console.log(`[SessionIndexer] Session ${sessionId} filtered as noise, skipping`);
      return { chunksIndexed: 0, skipped: 0 };
    }

    // Strip ANSI escape codes from terminal history before any processing
    if (checkpoint.terminalHistory) {
      checkpoint = { ...checkpoint, terminalHistory: stripAnsiCodes(checkpoint.terminalHistory) };
    }

    const projectPath = checkpoint.data?.snapshot?.projectPath;
    const projectName = projectPath ? getProjectName(projectPath) : undefined;
    const projectPrefix = projectName ? `[Project: ${projectName}] ` : '';

    let chunksIndexed = 0;

    // ---- Terminal Chunks ----
    if (checkpoint.terminalHistory) {
      const terminalChunks = chunkTerminalHistory(checkpoint.terminalHistory);
      console.log(`[SessionIndexer] Extracted ${terminalChunks.length} terminal chunks`);

      for (let i = 0; i < terminalChunks.length && chunksIndexed < MAX_CHUNKS_PER_SESSION; i++) {
        const chunk = terminalChunks[i];
        const content = redactSensitiveData(`${projectPrefix}${chunk.content}`);
        const contentHash = generateContentHash(content);

        await upsertMemoryChunk({
          id: randomUUID(),
          user_id: userId,
          source_type: 'ide_terminal_chunk',
          source_id: buildSourceId(sessionId, 'terminal', i),
          content,
          content_hash: contentHash,
          token_count: estimateTokens(content),
          heading: chunk.heading,
          section_type: chunk.sectionType,
        });

        chunksIndexed++;
      }
    }

    // ---- Error Chunks ----
    if (checkpoint.terminalHistory) {
      const errorChunks = extractErrors(checkpoint.terminalHistory);
      console.log(`[SessionIndexer] Extracted ${errorChunks.length} error chunks`);

      for (let i = 0; i < errorChunks.length && chunksIndexed < MAX_CHUNKS_PER_SESSION; i++) {
        const chunk = errorChunks[i];
        const content = redactSensitiveData(`${projectPrefix}${chunk.content}`);
        const contentHash = generateContentHash(content);

        await upsertMemoryChunk({
          id: randomUUID(),
          user_id: userId,
          source_type: 'ide_error',
          source_id: buildSourceId(sessionId, 'error', i),
          content,
          content_hash: contentHash,
          token_count: estimateTokens(content),
          heading: chunk.heading,
          section_type: 'error',
        });

        chunksIndexed++;
      }
    }

    // ---- File Change Chunks ----
    // Validate openFiles - detect bad data from Object.keys() on stringified JSON
    let validOpenFiles = checkpoint.openFiles || [];
    if (validOpenFiles.length > 0 && validOpenFiles.every(f => /^\d+$/.test(f))) {
      // All entries are numeric indices — bad data from Object.keys(string)
      validOpenFiles = extractFilePathsFromSnapshot(checkpoint.data?.snapshot?.files);
    }

    if (validOpenFiles.length > 0) {
      console.log(`[SessionIndexer] Indexing ${validOpenFiles.length} file changes`);

      for (let i = 0; i < validOpenFiles.length && chunksIndexed < MAX_CHUNKS_PER_SESSION; i++) {
        const filepath = validOpenFiles[i];
        const filename = filepath.split('/').pop() || filepath;
        const pName = projectName || 'unknown';

        const content = redactSensitiveData(
          `${projectPrefix}File: ${filepath}\nType: open\nProject: ${pName}`
        );
        const contentHash = generateContentHash(content);

        await upsertMemoryChunk({
          id: randomUUID(),
          user_id: userId,
          source_type: 'ide_file_change',
          source_id: buildSourceId(sessionId, 'file', i),
          content,
          content_hash: contentHash,
          token_count: estimateTokens(content),
          heading: filename,
          section_type: 'file_change',
        });

        chunksIndexed++;
      }
    }

    // ---- Session Summary ----
    if (chunksIndexed < MAX_CHUNKS_PER_SESSION) {
      const summaryParts: string[] = [];

      // Timestamp
      try {
        const date = new Date(checkpoint.timestamp);
        summaryParts.push(`Session on ${date.toISOString().split('T')[0]}`);
      } catch {
        summaryParts.push(`Session at ${checkpoint.timestamp}`);
      }

      // Branch
      if (checkpoint.gitBranch) {
        summaryParts.push(`Branch: ${checkpoint.gitBranch}`);
      }

      // Files (use validated openFiles)
      if (validOpenFiles.length > 0) {
        const fileNames = validOpenFiles
          .map((f) => f.split('/').pop() || f)
          .slice(0, 10);
        summaryParts.push(`Files: ${fileNames.join(', ')}`);
      }

      // Activity summary from terminal
      if (checkpoint.terminalHistory) {
        const snippet = checkpoint.terminalHistory.trim().substring(0, 200);
        summaryParts.push(`Activity: ${snippet}`);
      }

      // Session name or description
      if (checkpoint.name) {
        summaryParts.push(`Name: ${checkpoint.name}`);
      }
      if (checkpoint.description) {
        summaryParts.push(`Description: ${checkpoint.description}`);
      }

      const summaryContent = redactSensitiveData(`${projectPrefix}${summaryParts.join('\n')}`);
      const summaryHash = generateContentHash(summaryContent);

      const summaryHeading = checkpoint.name
        || (() => {
          try {
            return `Session ${new Date(checkpoint.timestamp).toISOString().split('T')[0]}`;
          } catch {
            return 'Session Summary';
          }
        })();

      await upsertMemoryChunk({
        id: randomUUID(),
        user_id: userId,
        source_type: 'ide_session_summary',
        source_id: buildSourceId(sessionId, 'summary', 0),
        content: summaryContent,
        content_hash: summaryHash,
        token_count: estimateTokens(summaryContent),
        heading: summaryHeading,
        section_type: 'session_summary',
      });

      chunksIndexed++;
    }

    console.log(
      `[SessionIndexer] Session ${sessionId} indexing complete: ${chunksIndexed} chunks indexed`
    );

    return { chunksIndexed, skipped: 0 };
  } catch (err) {
    console.error(`[SessionIndexer] Error indexing session ${sessionId}:`, err);
    throw err;
  } finally {
    indexingLocks.delete(sessionId);
  }
}
