import { NextRequest, NextResponse } from 'next/server';
import path from 'path';
import fs from 'fs/promises';

export const dynamic = 'force-dynamic';

interface TimelineEvent {
  id: string;
  timestamp: string | number;
  type: 'file_change' | 'terminal_command' | 'checkpoint' | 'error';
  description: string;
  details?: any;
}

// Get database connection using dynamic import to avoid webpack bundling issues
const getDatabase = async () => {
  const BetterSqlite3 = await import('better-sqlite3');
  const Database = BetterSqlite3.default || BetterSqlite3;
  const dbPath = path.join(process.cwd(), 'db', 'context-memory.db');
  return new Database(dbPath);
};

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const sessionId = searchParams.get('sessionId');
    
    let allCheckpoints: TimelineEvent[] = [];
    
    // 🔄 DUAL-READ: Try database first, fallback to JSON files
    let dbCheckpoints: TimelineEvent[] = [];
    let source = 'json_files';
    
    try {
      const db = await getDatabase();
      
      if (sessionId) {
        // Get checkpoints for specific session from database
        const rows = db.prepare(`
          SELECT * FROM checkpoints 
          WHERE session_id = ? 
          ORDER BY timestamp DESC
        `).all(sessionId);
        
        dbCheckpoints = rows.map((row: any) => ({
          id: row.id,
          timestamp: row.timestamp,
          type: 'checkpoint' as const,
          description: row.name || 'Checkpoint',
          details: {
            sessionId: row.session_id,
            description: row.description,
            terminalHistory: row.terminal_history,
            data: {
              terminalHistory: row.terminal_history,
              snapshot: row.files_snapshot ? JSON.parse(row.files_snapshot) : {}
            },
            metadata: row.metadata ? JSON.parse(row.metadata) : {}
          }
        }));
        
        source = 'database';
        console.log(`✅ Timeline loaded ${dbCheckpoints.length} checkpoints from database for session ${sessionId}`);
      } else {
        // Get recent checkpoints from all sessions
        const rows = db.prepare(`
          SELECT * FROM checkpoints 
          ORDER BY timestamp DESC 
          LIMIT 50
        `).all();
        
        dbCheckpoints = rows.map((row: any) => ({
          id: row.id,
          timestamp: row.timestamp,
          type: 'checkpoint' as const,
          description: row.name || 'Checkpoint',
          details: {
            sessionId: row.session_id,
            description: row.description,
            terminalHistory: row.terminal_history,
            data: {
              terminalHistory: row.terminal_history,
              snapshot: row.files_snapshot ? JSON.parse(row.files_snapshot) : {}
            },
            metadata: row.metadata ? JSON.parse(row.metadata) : {}
          }
        }));
        
        source = 'database';
        console.log(`✅ Timeline loaded ${dbCheckpoints.length} recent checkpoints from database`);
      }
      
      db.close();
      allCheckpoints = dbCheckpoints;
    } catch (dbError) {
      console.warn('⚠️ Database read failed, falling back to JSON files:', dbError);
    }
    
    // Fallback to JSON files if database returned no results
    if (allCheckpoints.length === 0) {
      const dataDir = path.join(process.cwd(), 'data');
      const sessionsDir = path.join(dataDir, 'sessions');
      
      try {
        if (sessionId) {
          // Get checkpoints for specific session from JSON files
          const checkpointsDir = path.join(sessionsDir, sessionId, 'checkpoints');
        
          try {
            const checkpointFiles = await fs.readdir(checkpointsDir);
            
            for (const file of checkpointFiles) {
              if (file.endsWith('.json')) {
                const checkpointData = JSON.parse(
                  await fs.readFile(path.join(checkpointsDir, file), 'utf8')
                );
                
                allCheckpoints.push({
                  id: checkpointData.id,
                  timestamp: checkpointData.timestamp,
                  type: 'checkpoint' as const,
                  description: checkpointData.name || 'Checkpoint',
                  details: {
                    sessionId: checkpointData.sessionId,
                    description: checkpointData.description,
                    data: checkpointData.data,
                    tags: checkpointData.tags,
                    autoGenerated: checkpointData.autoGenerated
                  }
                });
              }
            }
          } catch (error) {
            // Session or checkpoints directory doesn't exist, return empty
            console.log(`No JSON checkpoints found for session ${sessionId}, using database results`);
          }
          source = 'json_files';
        } else {
        // Get checkpoints from all sessions for comprehensive timeline
        try {
          const sessions = await fs.readdir(sessionsDir);
          
          // Limit to recent 5 sessions for performance
          const recentSessions = sessions.sort().slice(-5);
          
          for (const sessionDir of recentSessions) {
            const checkpointsDir = path.join(sessionsDir, sessionDir, 'checkpoints');
            const metadataPath = path.join(sessionsDir, sessionDir, 'metadata.json');
            
            let sessionName = sessionDir;
            try {
              const metadata = JSON.parse(await fs.readFile(metadataPath, 'utf8'));
              sessionName = metadata.name || sessionDir;
            } catch {
              // Metadata file doesn't exist, use directory name
            }
            
            try {
              const checkpointFiles = await fs.readdir(checkpointsDir);
              
              for (const file of checkpointFiles) {
                if (file.endsWith('.json')) {
                  const checkpointData = JSON.parse(
                    await fs.readFile(path.join(checkpointsDir, file), 'utf8')
                  );
                  
                  allCheckpoints.push({
                    id: checkpointData.id,
                    timestamp: checkpointData.timestamp,
                    type: 'checkpoint' as const,
                    description: `${sessionName}: ${checkpointData.name || 'Checkpoint'}`,
                    details: {
                      sessionId: checkpointData.sessionId,
                      sessionName,
                      description: checkpointData.description,
                      data: checkpointData.data,
                      tags: checkpointData.tags,
                      autoGenerated: checkpointData.autoGenerated
                    }
                  });
                }
              }
            } catch (error) {
              // Checkpoints directory doesn't exist for this session
              // logger?.warn(`No checkpoints found for session ${sessionDir}`);
            }
          }
        } catch (error) {
          // Sessions directory doesn't exist
          // logger?.warn('No sessions directory found');
        }
        source = 'json_files';
        }
      } catch (error) {
        // logger?.warn('Error reading session data:', error);
      }
    }
    
    // Sort by timestamp (newest first)
    allCheckpoints.sort((a, b) => {
      const timeA = typeof a.timestamp === 'string' ? new Date(a.timestamp).getTime() : a.timestamp;
      const timeB = typeof b.timestamp === 'string' ? new Date(b.timestamp).getTime() : b.timestamp;
      return timeB - timeA;
    });
    
    return NextResponse.json({ 
      success: true,
      events: allCheckpoints.slice(0, 50), // Return last 50 events
      total: allCheckpoints.length
    });
    
  } catch (error) {
    // logger?.error('Failed to fetch timeline:', error);
    return NextResponse.json(
      { error: 'Failed to fetch timeline' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const event = await request.json();
    
    const timelineEvent: TimelineEvent = {
      id: `event-${Date.now()}`,
      timestamp: new Date().toISOString(),
      ...event
    };
    
    // Save to global timeline file for tracking all events
    const dataDir = path.join(process.cwd(), 'data');
    const globalTimelineDir = path.join(dataDir, 'timeline');
    const globalTimelineFile = path.join(globalTimelineDir, 'global-timeline.json');
    
    await fs.mkdir(globalTimelineDir, { recursive: true });
    
    let globalTimeline = [];
    try {
      const existingData = await fs.readFile(globalTimelineFile, 'utf8');
      globalTimeline = JSON.parse(existingData);
    } catch {
      // File doesn't exist yet, start with empty array
      globalTimeline = [];
    }
    
    globalTimeline.push(timelineEvent);
    
    // Keep only last 1000 events for performance
    if (globalTimeline.length > 1000) {
      globalTimeline = globalTimeline.slice(-1000);
    }
    
    await fs.writeFile(globalTimelineFile, JSON.stringify(globalTimeline, null, 2));
    
    return NextResponse.json({ 
      success: true,
      event: timelineEvent
    });
    
  } catch (error) {
    // logger?.error('Failed to add timeline event:', error);
    return NextResponse.json(
      { error: 'Failed to add timeline event' },
      { status: 500 }
    );
  }
}