import { useEffect, useCallback, useRef } from 'react';
import { useSession } from '@/contexts/SessionContext';
import { useIDEStore } from '@/stores/useIDEStore';

/**
 * Automatic Checkpoint Hook
 * 
 * Creates automatic checkpoints every 10 minutes when changes are detected.
 * Checkpoints are saved to the auto/ subdirectory and cleaned up after 7 days.
 * 
 * Features:
 * - Timer-based checkpoints (configurable interval)
 * - Change detection (skips if no changes)
 * - Error handling with retry logic
 * - Automatic cleanup of old checkpoints
 * 
 * @param options Configuration options
 */

interface AutoCheckpointOptions {
  enabled?: boolean;
  interval?: number; // milliseconds
  sessionId?: string; // Optional explicit session ID (overrides context)
  onSuccess?: (checkpointId: string) => void;
  onError?: (error: Error) => void;
}

interface CheckpointState {
  lastCheckpointTime: number | null;
  lastTerminalLength: number;
  lastFileCount: number;
  lastActiveFile: string | null;
}

const DEFAULT_INTERVAL = 10 * 60 * 1000; // 10 minutes
const CHANGE_DETECTION_ENABLED = true;

export function useAutoCheckpoint(options: AutoCheckpointOptions = {}) {
  const {
    enabled = true,
    interval = DEFAULT_INTERVAL,
    sessionId: explicitSessionId,
    onSuccess,
    onError
  } = options;

  const { currentSession, sessionId: contextSessionId } = useSession();
  const stateRef = useRef<CheckpointState>({
    lastCheckpointTime: null,
    lastTerminalLength: 0,
    lastFileCount: 0,
    lastActiveFile: null
  });

  /**
   * Detect if there have been meaningful changes since last checkpoint
   */
  const hasChanges = useCallback((): boolean => {
    const state = useIDEStore.getState();
    const lastState = stateRef.current;

    // Always create first checkpoint
    if (lastState.lastCheckpointTime === null) {
      return true;
    }

    // Check for file changes
    const currentFileCount = state.openFiles?.length || 0;
    if (currentFileCount !== lastState.lastFileCount) {
      return true;
    }

    // Check for active file change
    if (state.activeFile !== lastState.lastActiveFile) {
      return true;
    }

    // Check for terminal activity (rough heuristic)
    const currentTerminalLength = state.terminalHistory?.length || 0;
    if (currentTerminalLength > lastState.lastTerminalLength) {
      return true;
    }

    return false;
  }, []);

  /**
   * Update state tracking after successful checkpoint
   */
  const updateState = useCallback(() => {
    const state = useIDEStore.getState();
    stateRef.current = {
      lastCheckpointTime: Date.now(),
      lastTerminalLength: state.terminalHistory?.length || 0,
      lastFileCount: state.openFiles?.length || 0,
      lastActiveFile: state.activeFile || null
    };
  }, []);

  /**
   * Create an automatic checkpoint
   */
  const createAutoCheckpoint = useCallback(async () => {
    // Priority: explicit > currentSession > contextSessionId
    const activeSessionId = explicitSessionId || currentSession?.id || contextSessionId;
    
    if (!activeSessionId) {
      console.log('⏭️ No active session, skipping auto-checkpoint');
      return;
    }

    // Change detection
    if (CHANGE_DETECTION_ENABLED && !hasChanges()) {
      console.log('⏭️ No changes detected, skipping auto-checkpoint');
      return;
    }

    try {
      const state = useIDEStore.getState();

      // Get terminal history from state or session
      const terminalHistory = state.terminalHistory || '';

      // Prepare checkpoint data
      const checkpointData = {
        sessionId: activeSessionId,
        autoGenerated: true,
        snapshot: {
          files: state.files || {},
          editor: {
            activeFile: state.activeFile,
            openFiles: state.openFiles || []
          }
        },
        terminalHistory,
        activeFile: state.activeFile
      };

      // Create checkpoint via API
      const response = await fetch('/api/checkpoint/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(checkpointData)
      });

      if (!response.ok) {
        throw new Error(`Checkpoint API failed: ${response.status}`);
      }

      const result = await response.json();

      if (result.success) {
        console.log(`✅ Auto-checkpoint created: ${result.checkpoint.id}`);
        updateState();
        onSuccess?.(result.checkpoint.id);

        // Trigger cleanup (async, non-blocking)
        cleanupOldCheckpoints(activeSessionId).catch(err => {
          console.warn('⚠️ Cleanup failed:', err);
        });
      } else {
        throw new Error('Checkpoint creation failed');
      }
    } catch (error) {
      console.error('❌ Auto-checkpoint failed:', error);
      onError?.(error as Error);
    }
  }, [explicitSessionId, currentSession, contextSessionId, hasChanges, updateState, onSuccess, onError]);

  /**
   * Cleanup old auto-checkpoints
   * - Keep last 50 checkpoints
   * - Delete anything older than 7 days
   */
  const cleanupOldCheckpoints = async (sessionId: string) => {
    try {
      const response = await fetch('/api/checkpoint/cleanup/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ sessionId })
      });

      if (response.ok) {
        const result = await response.json();
        if (result.deleted > 0) {
          console.log(`🧹 Cleaned up ${result.deleted} old auto-checkpoints, kept ${result.kept}`);
        }
      }
    } catch (error) {
      console.error('Cleanup error:', error);
    }
  };

  /**
   * Set up interval timer
   */
  useEffect(() => {
    // Priority: explicit > currentSession > contextSessionId
    const activeSessionId = explicitSessionId || currentSession?.id || contextSessionId;
    
    if (!enabled || !activeSessionId) {
      console.log(`⏭️ Auto-checkpoint disabled: enabled=${enabled}, sessionId=${activeSessionId}`);
      return;
    }

    console.log(`⏰ Auto-checkpoint timer started (interval: ${interval / 1000 / 60} minutes, sessionId: ${activeSessionId})`);

    // Create first checkpoint after 1 minute (not immediately)
    const initialTimeout = setTimeout(createAutoCheckpoint, 60 * 1000);

    // Then create on interval
    const intervalId = setInterval(createAutoCheckpoint, interval);

    return () => {
      clearTimeout(initialTimeout);
      clearInterval(intervalId);
      console.log('⏰ Auto-checkpoint timer stopped');
    };
  }, [enabled, explicitSessionId, currentSession, contextSessionId, interval, createAutoCheckpoint]);

  return {
    createNow: createAutoCheckpoint,
    enabled: enabled && !!(explicitSessionId || currentSession?.id || contextSessionId)
  };
}
