'use client';

import React, { useState, useEffect } from 'react';
import { 
  Brain, Search, Filter, Grid, List, Calendar, 
  Star, Download, Upload, Trash2, Edit2, Plus,
  ChevronLeft, ChevronRight, X, Check, Clock,
  Tag, FileText, Command, AlertCircle, Sparkles,
  Eye, Archive, Settings
} from 'lucide-react';
import Link from 'next/link';

interface Memory {
  id: number;
  title: string;
  description: string;
  type: string;
  confidence: number;
  tags: string[];
  context: any;
  starred: boolean;
  createdAt: string;
  updatedAt: string;
  autoGenerated: boolean;
}

interface MemoryStats {
  totalMemories: number;
  byType: Record<string, number>;
  averageConfidence: number;
  starred: number;
  todayMemories: number;
  thisWeekMemories: number;
}

export default function MemoriesPage() {
  const [memories, setMemories] = useState<Memory[]>([]);
  const [stats, setStats] = useState<MemoryStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
  const [filterType, setFilterType] = useState<string>('all');
  const [filterStarred, setFilterStarred] = useState(false);
  const [sortBy, setSortBy] = useState<'created_at' | 'confidence' | 'title'>('created_at');
  const [selectedMemories, setSelectedMemories] = useState<number[]>([]);
  const [editingMemory, setEditingMemory] = useState<Memory | null>(null);
  const [showFilters, setShowFilters] = useState(false);
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(0);
  const [isSearching, setIsSearching] = useState(false);

  const ITEMS_PER_PAGE = 12;

  // Load memories and stats on mount
  useEffect(() => {
    loadMemories();
    loadStats();
  }, [page, filterType, filterStarred, sortBy]);

  const loadMemories = async () => {
    try {
      setLoading(true);
      const params = new URLSearchParams({
        limit: ITEMS_PER_PAGE.toString(),
        offset: (page * ITEMS_PER_PAGE).toString(),
        orderBy: sortBy,
        orderDirection: 'DESC'
      });

      if (filterType !== 'all') {
        params.append('type', filterType);
      }
      
      if (filterStarred) {
        params.append('starred', 'true');
      }

      const response = await fetch(`/api/memories?${params}`);
      const data = await response.json();
      
      if (data.success) {
        setMemories(data.data);
        setTotalPages(Math.ceil(data.pagination.total / ITEMS_PER_PAGE));
      }
    } catch (error) {
      console.error('Failed to load memories:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadStats = async () => {
    try {
      const response = await fetch('/api/memories/stats');
      const data = await response.json();
      if (data.success) {
        setStats(data.data);
      }
    } catch (error) {
      console.error('Failed to load stats:', error);
    }
  };

  const handleSearch = async () => {
    if (!searchQuery.trim()) {
      loadMemories();
      return;
    }

    try {
      setIsSearching(true);
      const response = await fetch('/api/memories/search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query: searchQuery })
      });
      
      const data = await response.json();
      if (data.success) {
        setMemories(data.data);
      }
    } catch (error) {
      console.error('Search failed:', error);
    } finally {
      setIsSearching(false);
    }
  };

  const toggleStar = async (memory: Memory) => {
    try {
      const response = await fetch(`/api/memories/${memory.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ starred: !memory.starred })
      });
      
      if (response.ok) {
        loadMemories();
      }
    } catch (error) {
      console.error('Failed to toggle star:', error);
    }
  };

  const deleteMemory = async (id: number) => {
    if (!confirm('Are you sure you want to delete this memory?')) return;
    
    try {
      const response = await fetch(`/api/memories/${id}`, {
        method: 'DELETE'
      });
      
      if (response.ok) {
        loadMemories();
        loadStats();
      }
    } catch (error) {
      console.error('Failed to delete memory:', error);
    }
  };

  const exportMemories = async (format: 'json' | 'markdown' | 'html') => {
    try {
      const response = await fetch('/api/memories/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          ids: selectedMemories.length > 0 ? selectedMemories : undefined,
          format 
        })
      });
      
      if (format === 'json') {
        const data = await response.json();
        const blob = new Blob([JSON.stringify(data.data, null, 2)], { type: 'application/json' });
        downloadBlob(blob, `memories-export-${Date.now()}.json`);
      } else {
        const blob = await response.blob();
        const extension = format === 'markdown' ? 'md' : 'html';
        downloadBlob(blob, `memories-export-${Date.now()}.${extension}`);
      }
    } catch (error) {
      console.error('Export failed:', error);
    }
  };

  const downloadBlob = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getTypeIcon = (type: string) => {
    const icons: Record<string, JSX.Element> = {
      'bug-fix': <AlertCircle className="w-4 h-4 text-red-400" />,
      'feature-completion': <Sparkles className="w-4 h-4 text-green-400" />,
      'breakthrough': <Star className="w-4 h-4 text-yellow-400" />,
      'learning': <Brain className="w-4 h-4 text-blue-400" />,
      'architecture-decision': <Grid className="w-4 h-4 text-purple-400" />,
      'solution-discovery': <Eye className="w-4 h-4 text-orange-400" />
    };
    return icons[type] || <FileText className="w-4 h-4 text-gray-400" />;
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 0.7) return 'text-green-400';
    if (confidence >= 0.4) return 'text-yellow-400';
    return 'text-red-400';
  };

  return (
    <div className="min-h-screen bg-bg-primary text-text-primary">
      {/* Header */}
      <div className="border-b border-border-default">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link href="/ide" className="p-2 hover:bg-bg-secondary rounded transition-colors">
                <ChevronLeft className="w-5 h-5" />
              </Link>
              <h1 className="text-2xl font-bold flex items-center gap-2">
                <Brain className="w-6 h-6 text-orange-400" />
                Memory Management
              </h1>
            </div>
            
            <div className="flex items-center gap-2">
              <button
                onClick={() => window.location.href = '/memory-test'}
                className="p-2 hover:bg-bg-secondary rounded transition-colors"
                title="Test Detection"
              >
                <Settings className="w-5 h-5" />
              </button>
              <button
                onClick={() => exportMemories('json')}
                className="p-2 hover:bg-bg-secondary rounded transition-colors"
                title="Export"
              >
                <Download className="w-5 h-5" />
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Stats Bar */}
      {stats && (
        <div className="bg-bg-secondary border-b border-border-default">
          <div className="max-w-7xl mx-auto px-4 py-3">
            <div className="flex items-center justify-between text-sm">
              <div className="flex items-center gap-6">
                <div>
                  <span className="text-text-muted">Total:</span>{' '}
                  <span className="font-semibold">{stats.totalMemories}</span>
                </div>
                <div>
                  <span className="text-text-muted">Today:</span>{' '}
                  <span className="font-semibold text-green-400">{stats.todayMemories}</span>
                </div>
                <div>
                  <span className="text-text-muted">This Week:</span>{' '}
                  <span className="font-semibold text-blue-400">{stats.thisWeekMemories}</span>
                </div>
                <div>
                  <span className="text-text-muted">Starred:</span>{' '}
                  <span className="font-semibold text-yellow-400">{stats.starred}</span>
                </div>
                <div>
                  <span className="text-text-muted">Avg Confidence:</span>{' '}
                  <span className={`font-semibold ${getConfidenceColor(stats.averageConfidence)}`}>
                    {Math.round(stats.averageConfidence * 100)}%
                  </span>
                </div>
              </div>
              
              <div className="flex items-center gap-2">
                {Object.entries(stats.byType).map(([type, count]) => (
                  <div key={type} className="flex items-center gap-1">
                    {getTypeIcon(type)}
                    <span className="text-xs">{count}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Toolbar */}
      <div className="max-w-7xl mx-auto px-4 py-4">
        <div className="flex items-center justify-between mb-4">
          {/* Search */}
          <div className="flex items-center gap-2 flex-1 max-w-md">
            <div className="relative flex-1">
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                placeholder="Search memories..."
                className="w-full px-3 py-2 pl-9 bg-bg-secondary border border-border-default rounded text-text-primary placeholder-text-muted"
              />
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted" />
            </div>
            <button
              onClick={handleSearch}
              disabled={isSearching}
              className="px-4 py-2 bg-orange-500/20 text-orange-400 border border-orange-500/50 rounded hover:bg-orange-500/30 transition-colors disabled:opacity-50"
            >
              Search
            </button>
          </div>

          {/* Controls */}
          <div className="flex items-center gap-2">
            {/* View Mode */}
            <div className="flex items-center bg-bg-secondary border border-border-default rounded">
              <button
                onClick={() => setViewMode('grid')}
                className={`p-2 ${viewMode === 'grid' ? 'bg-orange-500/20 text-orange-400' : 'text-text-muted hover:text-text-primary'} transition-colors`}
                title="Grid View"
              >
                <Grid className="w-4 h-4" />
              </button>
              <button
                onClick={() => setViewMode('list')}
                className={`p-2 ${viewMode === 'list' ? 'bg-orange-500/20 text-orange-400' : 'text-text-muted hover:text-text-primary'} transition-colors`}
                title="List View"
              >
                <List className="w-4 h-4" />
              </button>
            </div>

            {/* Filters */}
            <button
              onClick={() => setShowFilters(!showFilters)}
              className={`p-2 ${showFilters ? 'bg-orange-500/20 text-orange-400' : 'hover:bg-bg-secondary'} border border-border-default rounded transition-colors`}
            >
              <Filter className="w-4 h-4" />
            </button>

            {/* Sort */}
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as any)}
              className="px-3 py-2 bg-bg-secondary border border-border-default rounded text-text-primary text-sm"
            >
              <option value="created_at">Newest First</option>
              <option value="confidence">Confidence</option>
              <option value="title">Title</option>
            </select>
          </div>
        </div>

        {/* Filter Panel */}
        {showFilters && (
          <div className="mb-4 p-4 bg-bg-secondary border border-border-default rounded">
            <div className="flex items-center gap-4">
              <div>
                <label className="block text-xs text-text-muted mb-1">Type</label>
                <select
                  value={filterType}
                  onChange={(e) => setFilterType(e.target.value)}
                  className="px-3 py-1 bg-bg-primary border border-border-default rounded text-sm"
                >
                  <option value="all">All Types</option>
                  <option value="bug-fix">Bug Fixes</option>
                  <option value="feature-completion">Features</option>
                  <option value="breakthrough">Breakthroughs</option>
                  <option value="learning">Learning</option>
                  <option value="architecture-decision">Architecture</option>
                  <option value="solution-discovery">Solutions</option>
                </select>
              </div>

              <div>
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={filterStarred}
                    onChange={(e) => setFilterStarred(e.target.checked)}
                    className="rounded border-border-default"
                  />
                  <span className="text-sm">Starred Only</span>
                </label>
              </div>
            </div>
          </div>
        )}

        {/* Memories Grid/List */}
        {loading ? (
          <div className="text-center py-12">
            <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-orange-400"></div>
          </div>
        ) : memories.length === 0 ? (
          <div className="text-center py-12">
            <Brain className="w-12 h-12 text-text-muted mx-auto mb-4" />
            <p className="text-text-muted">No memories found</p>
          </div>
        ) : (
          <div className={viewMode === 'grid' ? 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4' : 'space-y-2'}>
            {memories.map(memory => (
              <div
                key={memory.id}
                className={`bg-bg-secondary border border-border-default rounded-lg ${viewMode === 'grid' ? 'p-4' : 'p-3'} hover:border-orange-500/50 transition-all`}
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {getTypeIcon(memory.type)}
                    <h3 className="font-semibold text-text-primary line-clamp-1">
                      {memory.title}
                    </h3>
                  </div>
                  <div className="flex items-center gap-1">
                    <button
                      onClick={() => toggleStar(memory)}
                      className="p-1 hover:bg-bg-primary rounded transition-colors"
                    >
                      <Star className={`w-4 h-4 ${memory.starred ? 'text-yellow-400 fill-yellow-400' : 'text-text-muted'}`} />
                    </button>
                    <button
                      onClick={() => setEditingMemory(memory)}
                      className="p-1 hover:bg-bg-primary rounded transition-colors"
                    >
                      <Edit2 className="w-4 h-4 text-text-muted" />
                    </button>
                    <button
                      onClick={() => deleteMemory(memory.id)}
                      className="p-1 hover:bg-bg-primary rounded transition-colors"
                    >
                      <Trash2 className="w-4 h-4 text-red-400" />
                    </button>
                  </div>
                </div>

                {viewMode === 'grid' && (
                  <>
                    <p className="text-sm text-text-muted line-clamp-2 mb-3">
                      {memory.description || 'No description'}
                    </p>
                    
                    <div className="flex items-center justify-between text-xs">
                      <div className="flex items-center gap-2">
                        <span className={getConfidenceColor(memory.confidence)}>
                          {Math.round(memory.confidence * 100)}%
                        </span>
                        {memory.autoGenerated && (
                          <span className="text-blue-400" title="Auto-generated">
                            Auto
                          </span>
                        )}
                      </div>
                      <span className="text-text-muted">
                        {new Date(memory.createdAt).toLocaleDateString()}
                      </span>
                    </div>

                    {memory.tags.length > 0 && (
                      <div className="mt-2 flex flex-wrap gap-1">
                        {memory.tags.slice(0, 3).map(tag => (
                          <span key={tag} className="px-2 py-1 bg-bg-primary text-xs rounded">
                            {tag}
                          </span>
                        ))}
                        {memory.tags.length > 3 && (
                          <span className="px-2 py-1 text-xs text-text-muted">
                            +{memory.tags.length - 3}
                          </span>
                        )}
                      </div>
                    )}
                  </>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex items-center justify-center gap-2 mt-6">
            <button
              onClick={() => setPage(Math.max(0, page - 1))}
              disabled={page === 0}
              className="p-2 hover:bg-bg-secondary rounded transition-colors disabled:opacity-50"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <span className="text-sm">
              Page {page + 1} of {totalPages}
            </span>
            <button
              onClick={() => setPage(Math.min(totalPages - 1, page + 1))}
              disabled={page >= totalPages - 1}
              className="p-2 hover:bg-bg-secondary rounded transition-colors disabled:opacity-50"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        )}
      </div>
    </div>
  );
}