# Render Configuration for Coder1 IDE Alpha
# Optimized for Standard Plan ($25/month, 2GB RAM)

services:
  - type: web
    name: coder1-ide-alpha
    runtime: node
    region: oregon # or your preferred region
    plan: standard # $25/month plan - 2GB RAM
    
    # Build configuration with enhanced memory for Standard plan
    # Install build tools for native dependencies (node-pty, better-sqlite3)
    buildCommand: |
      apt-get update && apt-get install -y python3 make g++ build-essential
      NODE_OPTIONS="--max-old-space-size=1800" npm ci
      NODE_OPTIONS="--max-old-space-size=1800" npm run build:standalone
      rm -rf .next/cache node_modules/.cache
      npm prune --production
    
    # Start command with optimized memory for 2GB plan
    startCommand: NODE_OPTIONS="--max-old-space-size=1500 --expose-gc" node server.js
    
    # Health check
    healthCheckPath: /api/health
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
        
      - key: DEPLOYMENT_MODE
        value: alpha-limited
        
      - key: PORT
        value: 3001
        
      - key: NEXT_PUBLIC_API_URL
        generateValue: true # Render will generate the URL
        
      # Memory optimization for 2GB Standard plan
      - key: NODE_OPTIONS
        value: --max-old-space-size=1500
        
      # Session storage
      - key: DATABASE_URL
        value: sqlite:///data/coder1-sessions.db
        
      # Alpha configuration
      - key: ALPHA_MODE_ENABLED
        value: true
        
      - key: MAX_CONCURRENT_TEAMS
        value: 5  # Increased from 1 - we have more memory now
        
      - key: MAX_AGENTS_PER_TEAM
        value: 3  # Increased from 2 - we have more memory now
        
      # Add your alpha invite code
      - key: ALPHA_INVITE_CODE
        sync: false # Set this in Render dashboard for security
        
      # Monitoring
      - key: ENABLE_HEALTH_CHECKS
        value: true
        
      - key: MEMORY_PANIC_THRESHOLD_MB
        value: 1800  # Increased from 380 for 2GB plan

    # Auto-deploy from GitHub
    autoDeploy: false # Set to true after initial testing
    
    # Branch to deploy from
    branch: master # or your production branch
    
    # Number of instances (keep at 1 for alpha)
    numInstances: 1
    
    # Disk storage for session persistence
    disk:
      name: coder1-data
      mountPath: /data
      sizeGB: 1 # 1GB is plenty for alpha

# Optional: PostgreSQL database (if you want to upgrade from SQLite)
# Uncomment if you need more robust database storage
# databases:
#   - name: coder1-sessions
#     plan: starter # $7/month
#     region: oregon