# ============================================
# CODER1 IDE - RENDER DEPLOYMENT CONFIGURATION
# ============================================
# Production deployment for unified server architecture
# Optimized for Claude Code OAuth + Coder1 Bridge integration
# ============================================

services:
  - type: web
    name: coder1-ide-production
    runtime: node
    region: oregon # or your preferred region
    plan: starter # $7/month plan - sufficient for alpha testing
    
    # Build configuration with enhanced memory for Starter plan
    # Install build tools for native dependencies (node-pty)
    buildCommand: |
      apt-get update && apt-get install -y python3 make g++ build-essential
      NODE_OPTIONS="--max-old-space-size=1200" npm ci
      NODE_OPTIONS="--max-old-space-size=1200" npm run build
      rm -rf .next/cache node_modules/.cache
      npm prune --production
    
    # Start command with optimized memory for 512MB starter plan  
    startCommand: NODE_OPTIONS="--max-old-space-size=400 --expose-gc" node server.js
    
    # Health check
    healthCheckPath: /api/health
    
    # Environment variables
    envVars:
      # Core Configuration
      - key: NODE_ENV
        value: production
        
      - key: PORT
        value: 3001
        
      - key: HOSTNAME
        value: 0.0.0.0
        
      # Memory optimization for 512MB Starter plan
      - key: NODE_OPTIONS
        value: --max-old-space-size=400 --expose-gc
        
      - key: MEMORY_PANIC_THRESHOLD_MB
        value: 380
        
      # Service URLs (Render will auto-generate)
      - key: NEXT_PUBLIC_API_URL
        generateValue: true
        
      - key: NEXT_PUBLIC_UNIFIED_SERVER_URL
        generateValue: true
        
      - key: NEXT_PUBLIC_WEBSOCKET_URL
        generateValue: true
        
      # Claude Code OAuth Integration (NO API KEYS!)
      - key: CLAUDE_CODE_OAUTH_ENABLED
        value: true
        
      - key: CLAUDE_CODE_CLIENT_ID
        sync: false # Secret - set manually in Render dashboard
        
      - key: CLAUDE_CODE_CLIENT_SECRET  
        sync: false # Secret - set manually in Render dashboard
        
      - key: CLAUDE_CODE_REDIRECT_URI
        generateValue: true # Will use service URL + /auth/claude/callback
        
      # Coder1 Bridge Service Configuration
      - key: ENABLE_BRIDGE_SERVICE
        value: true
        
      - key: BRIDGE_AUTH_SECRET
        sync: false # Secret - generate and set in dashboard
        
      - key: BRIDGE_CONNECTION_TIMEOUT
        value: 30000
        
      # Alpha Configuration
      - key: ALPHA_MODE_ENABLED
        value: true
        
      - key: ALPHA_INVITE_CODE
        sync: false # Set this in Render dashboard for security
        
      - key: MAX_ALPHA_USERS
        value: 50
        
      # Database - SQLite for alpha, PostgreSQL for production
      - key: DATABASE_URL
        value: sqlite:///data/coder1-sessions.db
        
      # Security & Session Management
      - key: SESSION_SECRET
        sync: false # Secret - generate and set in dashboard
        
      - key: JWT_SECRET
        sync: false # Secret - generate and set in dashboard
        
      - key: SESSION_MAX_AGE
        value: 604800000 # 7 days
        
      # WebSocket Security
      - key: ENABLE_WS_AUTHENTICATION
        value: true
        
      - key: WS_AUTH_TIMEOUT
        value: 30000
        
      - key: WS_HEARTBEAT_INTERVAL
        value: 30000
        
      # Feature Flags (Alpha)
      - key: NEXT_PUBLIC_ENABLE_AI_CONSULTATION
        value: true
        
      - key: NEXT_PUBLIC_ENABLE_BRIDGE_DOWNLOAD
        value: true
        
      - key: NEXT_PUBLIC_ENABLE_LOCAL_SYNC
        value: true
        
      - key: NEXT_PUBLIC_ENABLE_AGENT_DASHBOARD
        value: false # Disabled for alpha
        
      # Monitoring & Performance
      - key: ENABLE_HEALTH_CHECKS
        value: true
        
      - key: HEALTH_CHECK_INTERVAL
        value: 30000
        
      - key: LOG_LEVEL
        value: info
        
      - key: ENABLE_PERFORMANCE_MONITORING
        value: true
        
      - key: MEMORY_CHECK_INTERVAL
        value: 60000

    # Auto-deploy from GitHub
    autoDeploy: false # Set to true after initial testing
    
    # Branch to deploy from
    branch: master # or your production branch
    
    # Number of instances (keep at 1 for alpha)
    numInstances: 1
    
    # Disk storage for session persistence
    disk:
      name: coder1-data
      mountPath: /data
      sizeGB: 1 # 1GB is plenty for alpha

# Optional: PostgreSQL database (if you want to upgrade from SQLite)
# Uncomment if you need more robust database storage
# databases:
#   - name: coder1-sessions
#     plan: starter # $7/month
#     region: oregon