'use client';

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { AlertTriangle, X, FileText, Check } from 'lucide-react';
import type { RuleSuggestion as RuleSuggestionType } from '@/services/johnny5/rule-suggester';

interface RuleSuggestionProps {
  isVisible: boolean;
  onDismiss: () => void;
}

const AUTO_HIDE_MS = 15_000;

/**
 * RuleSuggestion Component
 *
 * Compact dismissable banner that shows CLAUDE.md rule suggestions
 * generated by the RuleSuggester service. Listens to johnny5:ruleSuggestion
 * CustomEvents and displays one suggestion at a time (latest undismissed).
 *
 * Actions:
 *  - "Add to CLAUDE.md" dispatches johnny5:applyRule CustomEvent
 *  - "Dismiss" hides the banner and marks the suggestion dismissed
 */
export default function RuleSuggestion({ isVisible, onDismiss }: RuleSuggestionProps) {
  const [suggestion, setSuggestion] = useState<RuleSuggestionType | null>(null);
  const [show, setShow] = useState(false);
  const [applied, setApplied] = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const interactedRef = useRef(false);

  // -----------------------------------------------------------------------
  // Listen for new rule suggestions from the service
  // -----------------------------------------------------------------------
  useEffect(() => {
    if (typeof window === 'undefined') return;

    const handler = (e: Event) => {
      const detail = (e as CustomEvent<RuleSuggestionType>).detail;
      if (!detail || detail.dismissed || detail.applied) return;
      setSuggestion(detail);
      setShow(true);
      setApplied(false);
      interactedRef.current = false;
    };

    window.addEventListener('johnny5:ruleSuggestion', handler);
    return () => window.removeEventListener('johnny5:ruleSuggestion', handler);
  }, []);

  // -----------------------------------------------------------------------
  // Auto-hide after 15 seconds if not interacted with
  // -----------------------------------------------------------------------
  useEffect(() => {
    if (!show || !suggestion) return;

    if (timerRef.current) clearTimeout(timerRef.current);

    timerRef.current = setTimeout(() => {
      if (!interactedRef.current) {
        setShow(false);
      }
    }, AUTO_HIDE_MS);

    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [show, suggestion]);

  // -----------------------------------------------------------------------
  // Handlers
  // -----------------------------------------------------------------------
  const handleApply = useCallback(() => {
    if (!suggestion) return;
    interactedRef.current = true;
    setApplied(true);

    if (typeof window !== 'undefined') {
      window.dispatchEvent(
        new CustomEvent('johnny5:applyRule', {
          detail: { rule: suggestion.suggestedRule },
        }),
      );
    }

    // Fade out after a brief confirmation.
    setTimeout(() => {
      setShow(false);
      onDismiss();
    }, 1200);
  }, [suggestion, onDismiss]);

  const handleDismiss = useCallback(() => {
    interactedRef.current = true;
    setShow(false);
    onDismiss();
  }, [onDismiss]);

  const handleMouseEnter = useCallback(() => {
    interactedRef.current = true;
    if (timerRef.current) clearTimeout(timerRef.current);
  }, []);

  // -----------------------------------------------------------------------
  // Render
  // -----------------------------------------------------------------------
  if (!isVisible || !suggestion || !show) return null;

  const confidenceColor =
    suggestion.confidence === 'high'
      ? 'text-green-400'
      : suggestion.confidence === 'medium'
        ? 'text-yellow-400'
        : 'text-text-muted';

  return (
    <div
      onMouseEnter={handleMouseEnter}
      className={`
        mx-2 mb-2 rounded-lg overflow-hidden
        bg-amber-500/10 border border-amber-500/30
        transition-all duration-300 ease-out
        ${show ? 'animate-in slide-in-from-top opacity-100 translate-y-0' : 'opacity-0 -translate-y-2'}
      `}
    >
      {/* Header row */}
      <div className="flex items-center justify-between px-3 py-1.5">
        <div className="flex items-center gap-1.5">
          <AlertTriangle className="w-3.5 h-3.5 text-amber-400 flex-shrink-0" />
          <span className="text-[10px] font-semibold text-amber-400 uppercase tracking-wider">
            Rule Suggestion
          </span>
        </div>
        <button
          onClick={handleDismiss}
          className="text-text-muted hover:text-text-secondary transition-colors p-0.5"
          aria-label="Dismiss suggestion"
        >
          <X className="w-3 h-3" />
        </button>
      </div>

      {/* Rule text */}
      <div className="px-3 pb-2">
        <p className="text-xs text-text-primary font-mono leading-relaxed">
          {suggestion.suggestedRule}
        </p>

        {/* Metadata row */}
        <div className="flex items-center gap-3 mt-1.5 text-[10px] text-text-muted">
          <span>
            Seen <span className="text-amber-400 font-medium">{suggestion.occurrences}x</span>
          </span>
          <span className="text-border-default">|</span>
          <span className={confidenceColor}>
            {suggestion.confidence} confidence
          </span>
          <span className="text-border-default">|</span>
          <span>{suggestion.category}</span>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-2 mt-2">
          <button
            onClick={handleApply}
            disabled={applied}
            className={`
              flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-medium
              transition-all duration-200
              ${applied
                ? 'bg-green-500/20 text-green-400 cursor-default'
                : 'bg-coder1-cyan/20 text-coder1-cyan hover:bg-coder1-cyan/30 hover:shadow-[0_0_8px_rgba(0,217,255,0.15)]'
              }
            `}
          >
            {applied ? (
              <>
                <Check className="w-3 h-3" />
                Added
              </>
            ) : (
              <>
                <FileText className="w-3 h-3" />
                Add to CLAUDE.md
              </>
            )}
          </button>
          {!applied && (
            <button
              onClick={handleDismiss}
              className="
                flex items-center gap-1 px-2.5 py-1 rounded text-xs font-medium
                bg-bg-secondary text-text-muted
                hover:bg-bg-tertiary hover:text-text-secondary
                transition-all duration-200
              "
            >
              Dismiss
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
