/**
 * Memory Database Service
 * SQLite persistence layer for the memory system
 * Phase II: Database Implementation
 */

import Database from 'better-sqlite3';
import path from 'path';
import fs from 'fs';

export interface Memory {
  id?: number;
  title: string;
  description: string;
  type: 'bug-fix' | 'feature-completion' | 'breakthrough' | 'learning' | 'architecture-decision' | 'solution-discovery';
  confidence: number;
  tags: string[];
  context: {
    files: string[];
    commands: string[];
    errors?: string[];
    breakthroughs?: string[];
  };
  checkpointId?: string;
  sessionId?: string;
  autoGenerated: boolean;
  templateType: string;
  starred: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  deletedAt?: Date | null;
}

export interface MemoryEvent {
  id?: number;
  memoryId: number;
  eventType: string;
  eventData: any;
  confidence: number;
  files: string[];
  commands: string[];
  errors: string[];
  detectedAt?: Date;
  createdAt?: Date;
}

export interface MemoryAttachment {
  id?: number;
  memoryId: number;
  attachmentType: 'code-snippet' | 'screenshot' | 'terminal-output' | 'diff' | 'markdown' | 'link';
  content: string;
  metadata: any;
  createdAt?: Date;
}

export interface MemoryRelationship {
  id?: number;
  sourceMemoryId: number;
  targetMemoryId: number;
  relationshipType: 'related-to' | 'follows-from' | 'resolves' | 'causes' | 'implements' | 'references';
  createdAt?: Date;
}

export interface SearchOptions {
  query?: string;
  type?: Memory['type'];
  minConfidence?: number;
  tags?: string[];
  sessionId?: string;
  checkpointId?: string;
  starred?: boolean;
  dateFrom?: Date;
  dateTo?: Date;
  limit?: number;
  offset?: number;
  orderBy?: 'created_at' | 'updated_at' | 'confidence' | 'title';
  orderDirection?: 'ASC' | 'DESC';
}

export interface MemoryStats {
  totalMemories: number;
  byType: Record<string, number>;
  averageConfidence: number;
  autoGenerated: number;
  manuallyCreated: number;
  starred: number;
  recentMemories: number;
  todayMemories: number;
  thisWeekMemories: number;
  thisMonthMemories: number;
}

export class MemoryDatabase {
  private static instance: MemoryDatabase;
  private db: Database.Database;
  private dbPath: string;

  private constructor() {
    // Create database directory if it doesn't exist
    const dbDir = path.join(process.cwd(), 'data', 'db');
    if (!fs.existsSync(dbDir)) {
      fs.mkdirSync(dbDir, { recursive: true });
    }

    this.dbPath = path.join(dbDir, 'memories.db');
    this.db = new Database(this.dbPath);
    
    // Enable foreign keys
    this.db.pragma('foreign_keys = ON');
    
    // Initialize schema
    this.initializeSchema();
  }

  public static getInstance(): MemoryDatabase {
    if (!MemoryDatabase.instance) {
      MemoryDatabase.instance = new MemoryDatabase();
    }
    return MemoryDatabase.instance;
  }

  private initializeSchema(): void {
    const schemaPath = path.join(process.cwd(), 'db', 'schema', 'memories-schema.sql');
    
    if (fs.existsSync(schemaPath)) {
      const schema = fs.readFileSync(schemaPath, 'utf-8');
      // Split by semicolons but be careful with triggers
      const statements = schema.split(/;\s*(?=CREATE|DROP|INSERT|PRAGMA)/);
      
      for (const statement of statements) {
        if (statement.trim()) {
          try {
            this.db.exec(statement + ';');
          } catch (error) {
            console.error('Failed to execute schema statement:', error);
          }
        }
      }
    } else {
      console.warn('Schema file not found, creating basic tables');
      this.createBasicTables();
    }
  }

  private createBasicTables(): void {
    // Create minimal tables if schema file is missing
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS memories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        title TEXT NOT NULL,
        description TEXT,
        type TEXT NOT NULL,
        confidence REAL DEFAULT 0.5,
        tags TEXT,
        context TEXT,
        checkpoint_id TEXT,
        session_id TEXT,
        auto_generated BOOLEAN DEFAULT FALSE,
        template_type TEXT DEFAULT 'default',
        starred BOOLEAN DEFAULT FALSE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        deleted_at DATETIME
      );

      CREATE TABLE IF NOT EXISTS memory_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        memory_id INTEGER NOT NULL,
        event_type TEXT NOT NULL,
        event_data TEXT,
        confidence REAL DEFAULT 0.5,
        files TEXT,
        commands TEXT,
        errors TEXT,
        detected_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (memory_id) REFERENCES memories(id) ON DELETE CASCADE
      );
    `);
  }

  // ========================================
  // Memory CRUD Operations
  // ========================================

  public createMemory(memory: Omit<Memory, 'id' | 'createdAt' | 'updatedAt'>): Memory {
    const stmt = this.db.prepare(`
      INSERT INTO memories (
        title, description, type, confidence, tags, context,
        checkpoint_id, session_id, auto_generated, template_type, starred
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    const info = stmt.run(
      memory.title,
      memory.description,
      memory.type,
      memory.confidence,
      JSON.stringify(memory.tags),
      JSON.stringify(memory.context),
      memory.checkpointId || null,
      memory.sessionId || null,
      memory.autoGenerated ? 1 : 0,
      memory.templateType,
      memory.starred ? 1 : 0
    );

    return this.getMemory(info.lastInsertRowid as number)!;
  }

  public getMemory(id: number): Memory | null {
    const stmt = this.db.prepare(`
      SELECT * FROM memories WHERE id = ? AND deleted_at IS NULL
    `);
    
    const row = stmt.get(id) as any;
    return row ? this.mapRowToMemory(row) : null;
  }

  public updateMemory(id: number, updates: Partial<Memory>): Memory | null {
    const memory = this.getMemory(id);
    if (!memory) return null;

    const updatedMemory = { ...memory, ...updates };
    
    const stmt = this.db.prepare(`
      UPDATE memories SET
        title = ?, description = ?, type = ?, confidence = ?,
        tags = ?, context = ?, starred = ?, template_type = ?,
        updated_at = CURRENT_TIMESTAMP
      WHERE id = ? AND deleted_at IS NULL
    `);

    stmt.run(
      updatedMemory.title,
      updatedMemory.description,
      updatedMemory.type,
      updatedMemory.confidence,
      JSON.stringify(updatedMemory.tags),
      JSON.stringify(updatedMemory.context),
      updatedMemory.starred ? 1 : 0,
      updatedMemory.templateType,
      id
    );

    return this.getMemory(id);
  }

  public deleteMemory(id: number, soft: boolean = true): boolean {
    if (soft) {
      const stmt = this.db.prepare(`
        UPDATE memories SET deleted_at = CURRENT_TIMESTAMP WHERE id = ?
      `);
      const info = stmt.run(id);
      return info.changes > 0;
    } else {
      const stmt = this.db.prepare(`DELETE FROM memories WHERE id = ?`);
      const info = stmt.run(id);
      return info.changes > 0;
    }
  }

  public listMemories(options: SearchOptions = {}): { memories: Memory[]; total: number } {
    const {
      limit = 50,
      offset = 0,
      orderBy = 'created_at',
      orderDirection = 'DESC',
      type,
      minConfidence,
      starred,
      sessionId,
      checkpointId,
    } = options;

    let whereClause = 'deleted_at IS NULL';
    const params: any[] = [];

    if (type) {
      whereClause += ' AND type = ?';
      params.push(type);
    }
    
    if (minConfidence !== undefined) {
      whereClause += ' AND confidence >= ?';
      params.push(minConfidence);
    }
    
    if (starred !== undefined) {
      whereClause += ' AND starred = ?';
      params.push(starred ? 1 : 0);
    }
    
    if (sessionId) {
      whereClause += ' AND session_id = ?';
      params.push(sessionId);
    }
    
    if (checkpointId) {
      whereClause += ' AND checkpoint_id = ?';
      params.push(checkpointId);
    }

    // Count total
    const countStmt = this.db.prepare(`
      SELECT COUNT(*) as total FROM memories WHERE ${whereClause}
    `);
    const { total } = countStmt.get(...params) as any;

    // Get paginated results
    const stmt = this.db.prepare(`
      SELECT * FROM memories 
      WHERE ${whereClause}
      ORDER BY ${orderBy} ${orderDirection}
      LIMIT ? OFFSET ?
    `);

    const rows = stmt.all(...params, limit, offset) as any[];
    const memories = rows.map(row => this.mapRowToMemory(row));

    return { memories, total };
  }

  public searchMemories(query: string, options: SearchOptions = {}): Memory[] {
    const { limit = 50 } = options;
    
    const stmt = this.db.prepare(`
      SELECT m.* 
      FROM memories m
      JOIN memories_fts fts ON m.id = fts.rowid
      WHERE memories_fts MATCH ? 
        AND m.deleted_at IS NULL
      ORDER BY rank
      LIMIT ?
    `);

    const rows = stmt.all(query, limit) as any[];
    return rows.map(row => this.mapRowToMemory(row));
  }

  // ========================================
  // Memory Events
  // ========================================

  public addMemoryEvent(event: Omit<MemoryEvent, 'id' | 'createdAt'>): MemoryEvent {
    const stmt = this.db.prepare(`
      INSERT INTO memory_events (
        memory_id, event_type, event_data, confidence,
        files, commands, errors, detected_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);

    const info = stmt.run(
      event.memoryId,
      event.eventType,
      JSON.stringify(event.eventData),
      event.confidence,
      JSON.stringify(event.files),
      JSON.stringify(event.commands),
      JSON.stringify(event.errors),
      event.detectedAt || new Date()
    );

    return {
      ...event,
      id: info.lastInsertRowid as number,
      createdAt: new Date()
    };
  }

  public getMemoryEvents(memoryId: number): MemoryEvent[] {
    const stmt = this.db.prepare(`
      SELECT * FROM memory_events WHERE memory_id = ? ORDER BY created_at DESC
    `);
    
    const rows = stmt.all(memoryId) as any[];
    return rows.map(row => this.mapRowToEvent(row));
  }

  // ========================================
  // Statistics
  // ========================================

  public getStatistics(): MemoryStats {
    const statsStmt = this.db.prepare(`
      SELECT 
        COUNT(*) as totalMemories,
        COUNT(CASE WHEN auto_generated = 1 THEN 1 END) as autoGenerated,
        COUNT(CASE WHEN auto_generated = 0 THEN 1 END) as manuallyCreated,
        COUNT(CASE WHEN starred = 1 THEN 1 END) as starred,
        AVG(confidence) as averageConfidence,
        COUNT(CASE WHEN created_at >= datetime('now', '-1 day') THEN 1 END) as todayMemories,
        COUNT(CASE WHEN created_at >= datetime('now', '-7 days') THEN 1 END) as thisWeekMemories,
        COUNT(CASE WHEN created_at >= datetime('now', '-30 days') THEN 1 END) as thisMonthMemories,
        COUNT(CASE WHEN created_at >= datetime('now', '-30 days') THEN 1 END) as recentMemories
      FROM memories
      WHERE deleted_at IS NULL
    `);

    const stats = statsStmt.get() as any;

    const byTypeStmt = this.db.prepare(`
      SELECT type, COUNT(*) as count
      FROM memories
      WHERE deleted_at IS NULL
      GROUP BY type
    `);

    const byTypeRows = byTypeStmt.all() as any[];
    const byType: Record<string, number> = {};
    for (const row of byTypeRows) {
      byType[row.type] = row.count;
    }

    return {
      totalMemories: stats.totalMemories || 0,
      byType,
      averageConfidence: stats.averageConfidence || 0,
      autoGenerated: stats.autoGenerated || 0,
      manuallyCreated: stats.manuallyCreated || 0,
      starred: stats.starred || 0,
      recentMemories: stats.recentMemories || 0,
      todayMemories: stats.todayMemories || 0,
      thisWeekMemories: stats.thisWeekMemories || 0,
      thisMonthMemories: stats.thisMonthMemories || 0,
    };
  }

  // ========================================
  // Relationships
  // ========================================

  public addRelationship(relationship: Omit<MemoryRelationship, 'id' | 'createdAt'>): MemoryRelationship {
    const stmt = this.db.prepare(`
      INSERT INTO memory_relationships (
        source_memory_id, target_memory_id, relationship_type
      ) VALUES (?, ?, ?)
    `);

    const info = stmt.run(
      relationship.sourceMemoryId,
      relationship.targetMemoryId,
      relationship.relationshipType
    );

    return {
      ...relationship,
      id: info.lastInsertRowid as number,
      createdAt: new Date()
    };
  }

  public getRelatedMemories(memoryId: number, relationshipType?: string): Memory[] {
    let query = `
      SELECT m2.* 
      FROM memories m1
      JOIN memory_relationships mr ON m1.id = mr.source_memory_id
      JOIN memories m2 ON mr.target_memory_id = m2.id
      WHERE m1.id = ? AND m2.deleted_at IS NULL
    `;
    
    const params: any[] = [memoryId];
    
    if (relationshipType) {
      query += ' AND mr.relationship_type = ?';
      params.push(relationshipType);
    }

    const stmt = this.db.prepare(query);
    const rows = stmt.all(...params) as any[];
    return rows.map(row => this.mapRowToMemory(row));
  }

  // ========================================
  // Export/Import
  // ========================================

  public exportMemories(ids?: number[]): string {
    let query = 'SELECT * FROM memories WHERE deleted_at IS NULL';
    const params: any[] = [];

    if (ids && ids.length > 0) {
      query += ` AND id IN (${ids.map(() => '?').join(',')})`;
      params.push(...ids);
    }

    const stmt = this.db.prepare(query);
    const memories = stmt.all(...params).map(row => this.mapRowToMemory(row as any));

    // Get related data
    const exportData = {
      version: '1.0',
      exported_at: new Date().toISOString(),
      memories: memories.map(memory => ({
        ...memory,
        events: this.getMemoryEvents(memory.id!),
        relationships: this.db.prepare(
          'SELECT * FROM memory_relationships WHERE source_memory_id = ?'
        ).all(memory.id) as any[]
      }))
    };

    return JSON.stringify(exportData, null, 2);
  }

  public importMemories(jsonData: string): { imported: number; failed: number } {
    const data = JSON.parse(jsonData);
    let imported = 0;
    let failed = 0;

    const transaction = this.db.transaction((memories: any[]) => {
      for (const memoryData of memories) {
        try {
          const { events, relationships, ...memory } = memoryData;
          
          // Import memory
          const newMemory = this.createMemory(memory);
          
          // Import events
          if (events) {
            for (const event of events) {
              this.addMemoryEvent({ ...event, memoryId: newMemory.id! });
            }
          }
          
          imported++;
        } catch (error) {
          console.error('Failed to import memory:', error);
          failed++;
        }
      }
    });

    transaction(data.memories);
    
    return { imported, failed };
  }

  // ========================================
  // Helper Methods
  // ========================================

  private mapRowToMemory(row: any): Memory {
    return {
      id: row.id,
      title: row.title,
      description: row.description,
      type: row.type,
      confidence: row.confidence,
      tags: JSON.parse(row.tags || '[]'),
      context: JSON.parse(row.context || '{}'),
      checkpointId: row.checkpoint_id,
      sessionId: row.session_id,
      autoGenerated: row.auto_generated === 1,
      templateType: row.template_type,
      starred: row.starred === 1,
      createdAt: new Date(row.created_at),
      updatedAt: new Date(row.updated_at),
      deletedAt: row.deleted_at ? new Date(row.deleted_at) : null
    };
  }

  private mapRowToEvent(row: any): MemoryEvent {
    return {
      id: row.id,
      memoryId: row.memory_id,
      eventType: row.event_type,
      eventData: JSON.parse(row.event_data || '{}'),
      confidence: row.confidence,
      files: JSON.parse(row.files || '[]'),
      commands: JSON.parse(row.commands || '[]'),
      errors: JSON.parse(row.errors || '[]'),
      detectedAt: row.detected_at ? new Date(row.detected_at) : undefined,
      createdAt: new Date(row.created_at)
    };
  }

  public close(): void {
    this.db.close();
  }
}

// Export singleton instance
export const memoryDb = MemoryDatabase.getInstance();