/**
 * Johnny5 Session Memory Integration Test
 *
 * Tests the full end-to-end pipeline:
 * 1. Index a test checkpoint into memory_chunks
 * 2. Search for it via keyword search
 * 3. Verify query intent routing works
 * 4. Clean up test data
 *
 * Run with: npx tsx __tests__/session-memory-integration.test.ts
 */

import { randomUUID } from 'crypto';

// ============================================================================
// Minimal Test Framework
// ============================================================================

let passed = 0;
let failed = 0;
let total = 0;
const errors: string[] = [];

async function it(name: string, fn: () => Promise<void>) {
  total++;
  try {
    await fn();
    passed++;
    console.log(`  ✅ ${name}`);
  } catch (err: any) {
    failed++;
    const msg = err.message || String(err);
    console.log(`  ❌ ${name}`);
    console.log(`     ${msg}`);
    errors.push(`${name}: ${msg}`);
  }
}

function expect(actual: any) {
  return {
    toBe: (expected: any) => {
      if (actual !== expected) throw new Error(`Expected ${JSON.stringify(actual)} to be ${JSON.stringify(expected)}`);
    },
    toBeGreaterThan: (n: number) => {
      if (!(actual > n)) throw new Error(`Expected ${actual} > ${n}`);
    },
    toBeGreaterThanOrEqual: (n: number) => {
      if (!(actual >= n)) throw new Error(`Expected ${actual} >= ${n}`);
    },
    toBeTruthy: () => {
      if (!actual) throw new Error(`Expected truthy, got ${JSON.stringify(actual)}`);
    },
    toContain: (s: string) => {
      if (typeof actual === 'string' && !actual.includes(s)) throw new Error(`Expected "${actual.substring(0, 80)}..." to contain "${s}"`);
    },
    not: {
      toContain: (s: string) => {
        if (typeof actual === 'string' && actual.includes(s)) throw new Error(`Expected NOT to contain "${s}"`);
      },
    },
  };
}

// ============================================================================
// Test Data
// ============================================================================

const TEST_SESSION_ID = `test_session_${Date.now()}`;
const TEST_USER_ID = 'test_user';

const testCheckpoint = {
  id: randomUUID(),
  sessionId: TEST_SESSION_ID,
  name: 'Test: CORS Bug Fix Session',
  description: 'Fixed CORS configuration in Express server',
  timestamp: new Date().toISOString(),
  terminalHistory: `
$ npm run build
> next build

✓ Compiled successfully in 12.3s

$ git status
On branch fix/cors-headers
Changes to be committed:
  modified:   server.js
  modified:   lib/cors-config.ts
  new file:   middleware/cors-middleware.ts

$ npm test
PASS tests/cors.test.ts
  ✓ allows requests from allowed origins (12ms)
  ✓ blocks requests from unknown origins (3ms)
  ✓ handles preflight OPTIONS requests (5ms)

Error: CORS policy violation detected
  at CorsMiddleware.validate (cors-middleware.ts:45:12)
  at processRequest (server.js:178:8)

$ git commit -m "fix: CORS configuration for production domains"
[fix/cors-headers abc1234] fix: CORS configuration for production domains
 3 files changed, 47 insertions(+), 12 deletions(-)
`,
  openFiles: [
    '/Users/mike/project/server.js',
    '/Users/mike/project/lib/cors-config.ts',
    '/Users/mike/project/middleware/cors-middleware.ts',
  ],
  gitBranch: 'fix/cors-headers',
  autoGenerated: false,
  data: {
    activeFile: '/Users/mike/project/lib/cors-config.ts',
    snapshot: {
      projectPath: '/Users/mike/project',
      files: {
        'server.js': { modified: true },
        'lib/cors-config.ts': { modified: true },
        'middleware/cors-middleware.ts': { created: true },
      },
    },
  },
};

// ============================================================================
// Tests
// ============================================================================

async function runTests() {
  console.log('\n🧪 Session Memory Integration Tests\n');
  console.log('='.repeat(50));

  // Import modules (after DB initialization)
  const { indexSessionFromCheckpoint } = await import('../services/memory/session-indexer');
  const { getDb } = await import('../lib/johnny5-db');
  const { detectSessionQueryIntent, allocateTokenBudget } = await import('../services/memory/search/query-intent');

  const db = getDb();

  // --------------------------------------------------------------------------
  // Test 1: Indexing Pipeline
  // --------------------------------------------------------------------------

  console.log('\n📋 Indexing Pipeline\n');

  await it('indexes a test checkpoint with terminal, files, errors, and summary', async () => {
    const result = await indexSessionFromCheckpoint(testCheckpoint as any, TEST_SESSION_ID, TEST_USER_ID);
    expect(result.chunksIndexed).toBeGreaterThan(0);
    console.log(`     Indexed ${result.chunksIndexed} chunks`);
  });

  await it('creates chunks in the database with correct source_type', async () => {
    const rows = db.prepare(
      `SELECT source_type, COUNT(*) as count FROM memory_chunks WHERE source_id LIKE ? GROUP BY source_type ORDER BY count DESC`
    ).all(`ide:${TEST_SESSION_ID}:%`) as { source_type: string; count: number }[];

    expect(rows.length).toBeGreaterThan(0);

    for (const row of rows) {
      console.log(`     ${row.source_type}: ${row.count} chunks`);
    }
  });

  await it('creates terminal chunks', async () => {
    const count = db.prepare(
      `SELECT COUNT(*) as count FROM memory_chunks WHERE source_id LIKE ? AND source_type = 'ide_terminal_chunk'`
    ).get(`ide:${TEST_SESSION_ID}:%`) as { count: number };

    expect(count.count).toBeGreaterThan(0);
  });

  await it('creates error chunks from terminal errors', async () => {
    const count = db.prepare(
      `SELECT COUNT(*) as count FROM memory_chunks WHERE source_id LIKE ? AND source_type = 'ide_error'`
    ).get(`ide:${TEST_SESSION_ID}:%`) as { count: number };

    expect(count.count).toBeGreaterThan(0);
  });

  await it('creates file change chunks', async () => {
    const count = db.prepare(
      `SELECT COUNT(*) as count FROM memory_chunks WHERE source_id LIKE ? AND source_type = 'ide_file_change'`
    ).get(`ide:${TEST_SESSION_ID}:%`) as { count: number };

    expect(count.count).toBeGreaterThan(0);
  });

  await it('creates a session summary chunk', async () => {
    const count = db.prepare(
      `SELECT COUNT(*) as count FROM memory_chunks WHERE source_id LIKE ? AND source_type = 'ide_session_summary'`
    ).get(`ide:${TEST_SESSION_ID}:%`) as { count: number };

    expect(count.count).toBe(1);
  });

  await it('enriches chunks with project name prefix', async () => {
    const chunk = db.prepare(
      `SELECT content FROM memory_chunks WHERE source_id LIKE ? AND source_type = 'ide_session_summary' LIMIT 1`
    ).get(`ide:${TEST_SESSION_ID}:%`) as { content: string } | undefined;

    expect(chunk).toBeTruthy();
    expect(chunk!.content).toContain('[Project: project]');
  });

  await it('redacts sensitive data in indexed content', async () => {
    // Create a checkpoint with a secret
    const secretCheckpoint = {
      ...testCheckpoint,
      id: randomUUID(),
      sessionId: `${TEST_SESSION_ID}_secret`,
      terminalHistory: `
$ export ANTHROPIC_API_KEY=sk-ant-secret123
$ npm run build
Build successful
`,
      openFiles: [],
    };

    const result = await indexSessionFromCheckpoint(secretCheckpoint as any, `${TEST_SESSION_ID}_secret`, TEST_USER_ID);
    expect(result.chunksIndexed).toBeGreaterThan(0);

    // Check that content doesn't contain the secret
    const chunks = db.prepare(
      `SELECT content FROM memory_chunks WHERE source_id LIKE ?`
    ).all(`ide:${TEST_SESSION_ID}_secret:%`) as { content: string }[];

    for (const chunk of chunks) {
      expect(chunk.content).not.toContain('sk-ant-secret123');
    }
  });

  // --------------------------------------------------------------------------
  // Test 2: Deduplication (re-indexing same session)
  // --------------------------------------------------------------------------

  console.log('\n📋 Deduplication\n');

  await it('skips re-indexing auto-generated checkpoints for already-indexed sessions', async () => {
    const autoCheckpoint = {
      ...testCheckpoint,
      autoGenerated: true,
    };

    const result = await indexSessionFromCheckpoint(autoCheckpoint as any, TEST_SESSION_ID, TEST_USER_ID);
    expect(result.chunksIndexed).toBe(0);
    expect(result.skipped).toBeGreaterThan(0);
  });

  await it('allows re-indexing manual checkpoints for already-indexed sessions', async () => {
    const manualCheckpoint = {
      ...testCheckpoint,
      autoGenerated: false,
    };

    const before = db.prepare(
      `SELECT COUNT(*) as count FROM memory_chunks WHERE source_id LIKE ?`
    ).get(`ide:${TEST_SESSION_ID}:%`) as { count: number };

    const result = await indexSessionFromCheckpoint(manualCheckpoint as any, TEST_SESSION_ID, TEST_USER_ID);
    // Manual re-index should proceed (chunks may be deduped by content hash)
    expect(result.chunksIndexed).toBeGreaterThanOrEqual(0);
  });

  // --------------------------------------------------------------------------
  // Test 3: Noise Filtering
  // --------------------------------------------------------------------------

  console.log('\n📋 Noise Filtering\n');

  await it('skips sessions with only navigation commands', async () => {
    const noiseCheckpoint = {
      id: randomUUID(),
      sessionId: `${TEST_SESSION_ID}_noise`,
      timestamp: new Date().toISOString(),
      terminalHistory: 'cd /Users/mike/project\nls\npwd\nclear\nls -la',
    };

    const result = await indexSessionFromCheckpoint(noiseCheckpoint as any, `${TEST_SESSION_ID}_noise`, TEST_USER_ID);
    expect(result.chunksIndexed).toBe(0);
  });

  await it('skips sessions with no meaningful content', async () => {
    const emptyCheckpoint = {
      id: randomUUID(),
      sessionId: `${TEST_SESSION_ID}_empty`,
      timestamp: new Date().toISOString(),
    };

    const result = await indexSessionFromCheckpoint(emptyCheckpoint as any, `${TEST_SESSION_ID}_empty`, TEST_USER_ID);
    expect(result.chunksIndexed).toBe(0);
  });

  // --------------------------------------------------------------------------
  // Test 4: Keyword Search Integration
  // --------------------------------------------------------------------------

  console.log('\n📋 Keyword Search\n');

  await it('finds indexed session data via keyword search for "CORS"', async () => {
    const { searchMemoryKeyword } = await import('../lib/johnny5-db');

    const results = await searchMemoryKeyword('CORS', 10, TEST_USER_ID);
    expect(results.length).toBeGreaterThan(0);

    // Should find chunks about CORS from our test session
    const hasSessionResult = results.some(r => r.source_id.includes(TEST_SESSION_ID));
    expect(hasSessionResult).toBeTruthy();
    console.log(`     Found ${results.length} results, ${results.filter(r => r.source_id.includes(TEST_SESSION_ID)).length} from test session`);
  });

  await it('finds indexed session data via keyword search for "cors-config.ts"', async () => {
    const { searchMemoryKeyword } = await import('../lib/johnny5-db');

    const results = await searchMemoryKeyword('cors-config.ts', 10, TEST_USER_ID);
    const hasSessionResult = results.some(r => r.source_id.includes(TEST_SESSION_ID));
    expect(hasSessionResult).toBeTruthy();
  });

  // --------------------------------------------------------------------------
  // Test 5: Query Intent → Search Routing
  // --------------------------------------------------------------------------

  console.log('\n📋 Intent-Aware Search Routing\n');

  await it('routes "what errors did I hit" to error intent with ide_error boost', () => {
    const intent = detectSessionQueryIntent('what errors did I hit');
    expect(intent.intent).toBe('error');
    expect(intent.preferredSourceTypes[0]).toBe('ide_error');

    const budget = allocateTokenBudget(intent.intent, 2000);
    expect(budget.sessionBudget).toBe(1400); // 70% for error queries
  });

  await it('routes "what files did I change" to file_change intent', () => {
    const intent = detectSessionQueryIntent('what files did I change');
    expect(intent.intent).toBe('file_change');
    expect(intent.preferredSourceTypes[0]).toBe('ide_file_change');
  });

  await it('routes "remember when I fixed the CORS bug" to session_recall', () => {
    const intent = detectSessionQueryIntent('remember when I fixed the CORS bug');
    expect(intent.intent).toBe('session_recall');
  });

  // --------------------------------------------------------------------------
  // Cleanup
  // --------------------------------------------------------------------------

  console.log('\n📋 Cleanup\n');

  await it('cleans up test data', async () => {
    const deleteIds = [
      `ide:${TEST_SESSION_ID}:%`,
      `ide:${TEST_SESSION_ID}_secret:%`,
      `ide:${TEST_SESSION_ID}_noise:%`,
      `ide:${TEST_SESSION_ID}_empty:%`,
    ];

    let totalDeleted = 0;
    for (const pattern of deleteIds) {
      const result = db.prepare(`DELETE FROM memory_chunks WHERE source_id LIKE ?`).run(pattern);
      totalDeleted += result.changes;
    }

    console.log(`     Deleted ${totalDeleted} test chunks`);
    expect(totalDeleted).toBeGreaterThan(0);
  });

  // --------------------------------------------------------------------------
  // Results
  // --------------------------------------------------------------------------

  console.log('\n' + '='.repeat(50));
  console.log(`\n📊 Results: ${passed} passed, ${failed} failed, ${total} total\n`);

  if (errors.length > 0) {
    console.log('❌ Failures:\n');
    for (const err of errors) {
      console.log(`  ${err}`);
    }
  }

  if (failed === 0) {
    console.log('✅ All integration tests passed!\n');
  }

  process.exit(failed > 0 ? 1 : 0);
}

runTests().catch((err) => {
  console.error('Test runner error:', err);
  process.exit(1);
});
