'use client';

import React, { useState, useEffect } from 'react';
import { Save, Clock, Download, FileText, BookOpen, GitBranch, Check, Loader2, X, Eye } from 'lucide-react';
import { glows } from '@/lib/design-tokens';
import { useSessionSummary } from '@/lib/hooks/useSessionSummary';
import { useSupervision } from '@/contexts/SupervisionContext';

interface StatusBarProps {
  activeFile?: string | null;
  isConnected?: boolean;
  openFiles?: any[];
  terminalHistory?: string;
  terminalCommands?: string[];
}

export default function StatusBar({ 
  activeFile, 
  isConnected = false, 
  openFiles = [], 
  terminalHistory = '', 
  terminalCommands = [] 
}: StatusBarProps) {
  const [lastCheckpoint, setLastCheckpoint] = useState<Date | null>(null);
  const [isLoading, setIsLoading] = useState<string | null>(null);
  const [sessionId, setSessionId] = useState<string>('');
  const [toastMessage, setToastMessage] = useState<string>('');
  const [showSessionModal, setShowSessionModal] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);
  const [exportFormat, setExportFormat] = useState<'markdown' | 'json' | 'html' | 'all'>('markdown');
  const [activeTab, setActiveTab] = useState<'summary' | 'insights' | 'nextSteps'>('summary');
  const [storeSuccess, setStoreSuccess] = useState(false);
  const [isStoringInDocs, setIsStoringInDocs] = useState(false);

  const {
    isGenerating,
    summary,
    insights,
    nextSteps,
    error: summaryError,
    hasGenerated,
    progress,
    currentStep,
    generateSummary,
    clearSummary,
    copySummaryToClipboard,
    exportSummary,
    storeInDocumentation
  } = useSessionSummary();
  
  // Get supervision state from context
  const { isSupervisionActive, supervisionStatus, lastSupervisionCheck } = useSupervision();

  // Initialize sessionId on mount
  useEffect(() => {
    let storedSessionId = localStorage.getItem('currentSessionId');
    if (!storedSessionId) {
      storedSessionId = `session_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
      localStorage.setItem('currentSessionId', storedSessionId);
    }
    setSessionId(storedSessionId);
  }, []);

  // Auto-checkpoint every 10 minutes
  useEffect(() => {
    if (!sessionId) return;

    const autoCheckpoint = async () => {
      try {
        // Only auto-checkpoint if there's meaningful activity
        const hasActivity = localStorage.getItem('openFiles') || 
                           localStorage.getItem('terminalHistory') || 
                           localStorage.getItem('editorContent');
        
        if (!hasActivity) return;

        await fetch('/api/checkpoint', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            sessionId,
            timestamp: new Date().toISOString(),
            activeFile,
            snapshot: {
              files: localStorage.getItem('openFiles') || '[]',
              terminal: localStorage.getItem('terminalHistory') || '',
              editor: localStorage.getItem('editorContent') || ''
            },
            autoGenerated: true
          })
        });

        const now = new Date();
        setLastCheckpoint(now);
        console.log('🕐 Auto-checkpoint saved at:', now.toLocaleTimeString());
      } catch (error) {
        console.error('Auto-checkpoint failed:', error);
      }
    };

    // Set up interval for auto-checkpoints (10 minutes)
    const interval = setInterval(autoCheckpoint, 10 * 60 * 1000); // 10 minutes

    // Also create initial checkpoint after 30 seconds (to catch early work)
    const initialTimeout = setTimeout(autoCheckpoint, 30 * 1000);

    return () => {
      clearInterval(interval);
      clearTimeout(initialTimeout);
    };
  }, [sessionId, activeFile]);

  // Show toast message
  const showToast = (message: string) => {
    setToastMessage(message);
    setTimeout(() => setToastMessage(''), 3000);
  };

  const handleCheckpoint = async () => {
    setIsLoading('checkpoint');
    const now = new Date();
    
    try {
      // Use Next.js API route that proxies to Express
      const response = await fetch('/api/checkpoint', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId,
          timestamp: now.toISOString(),
          activeFile,
          snapshot: {
            files: localStorage.getItem('openFiles') || '[]',
            terminal: localStorage.getItem('terminalHistory') || '',
            editor: localStorage.getItem('editorContent') || ''
          },
          autoGenerated: false
        })
      });
      
      if (response.ok) {
        const data = await response.json();
        if (data.sessionId) {
          // Update sessionId if a new one was created
          localStorage.setItem('currentSessionId', data.sessionId);
          setSessionId(data.sessionId);
        }
        setLastCheckpoint(now);
        showToast('✅ Checkpoint saved successfully');
        console.log('✅ Checkpoint saved at:', now.toLocaleTimeString());
      } else {
        throw new Error('Failed to save checkpoint');
      }
    } catch (error) {
      console.error('Failed to save checkpoint:', error);
      showToast('⚠️ Failed to save checkpoint');
    }
    
    setIsLoading(null);
  };

  const handleTimeline = async () => {
    setIsLoading('timeline');
    
    try {
      // Use Next.js API route with sessionId
      const response = await fetch(`/api/timeline?sessionId=${sessionId}`);
      const data = await response.json();
      
      if (response.ok) {
        console.log('📊 Timeline data:', data);
        // Open timeline page with sessionId
        window.open(`/timeline?sessionId=${sessionId}`, '_blank');
        showToast('📊 Opening timeline view');
      } else {
        throw new Error('Failed to fetch timeline');
      }
    } catch (error) {
      console.error('Failed to fetch timeline:', error);
      showToast('⚠️ Failed to load timeline');
    }
    
    setIsLoading(null);
  };

  const handleExport = async () => {
    setIsLoading('export');
    
    try {
      // Use Next.js API route with sessionId for session export
      const response = await fetch('/api/export', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          format: 'zip',
          includeNodeModules: false,
          includeGitHistory: true,
          sessionId // Include sessionId for session data export
        })
      });
      
      if (response.ok) {
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `export-${sessionId}-${Date.now()}.${sessionId ? 'json' : 'zip'}`;
        a.click();
        window.URL.revokeObjectURL(url);
        showToast('📦 Export completed successfully');
        console.log('📦 Project exported successfully');
      } else {
        throw new Error('Failed to export');
      }
    } catch (error) {
      console.error('Failed to export project:', error);
      showToast('⚠️ Failed to export project');
    }
    
    setIsLoading(null);
  };

  const handleSessionSummary = async () => {
    setShowSessionModal(true);
    setCopySuccess(false);
    setActiveTab('summary');
    
    // Clear previous results if regenerating
    if (hasGenerated) {
      clearSummary();
    }

    // Start generation with current session data
    await generateSummary({
      openFiles,
      activeFile,
      terminalHistory,
      terminalCommands
    });
  };

  // Handle copy to clipboard with success feedback
  const handleCopyToClipboard = async () => {
    const content = activeTab === 'summary' ? summary :
                   activeTab === 'insights' ? insights : nextSteps;
    const success = await copySummaryToClipboard(content || '');
    if (success) {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    }
  };

  // Store session summary in Documentation Intelligence System
  const handleStoreInDocs = async () => {
    setIsStoringInDocs(true);
    setStoreSuccess(false);
    
    const success = await storeInDocumentation();
    if (success) {
      setStoreSuccess(true);
      setTimeout(() => setStoreSuccess(false), 3000);
    }
    
    setIsStoringInDocs(false);
  };

  // Handle export button click
  const handleExportSummary = async () => {
    const success = await exportSummary(exportFormat);
    if (success) {
      showToast('📦 Export completed successfully');
    } else {
      showToast('⚠️ Failed to export summary');
    }
  };

  // Close modal and reset state
  const handleCloseModal = () => {
    setShowSessionModal(false);
    setCopySuccess(false);
    setActiveTab('summary');
  };

  const handleDocs = async () => {
    // Open the documentation page in a new tab
    window.open('/documentation', '_blank');
  };

  return (
    <>
      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-14 right-4 bg-bg-secondary border border-border-default rounded-lg px-4 py-2 shadow-lg z-50 animate-fade-in">
          <span className="text-sm text-text-primary">{toastMessage}</span>
        </div>
      )}
      
      <div className="h-11 bg-bg-secondary border-t border-border-default flex items-center justify-between px-4">
      {/* Left section - Status info */}
      <div className="flex items-center gap-4 text-sm text-text-muted">
        <div className="flex items-center gap-1">
          <div className={`w-2.5 h-2.5 rounded-full ${isConnected ? 'bg-green-400' : 'bg-gray-400'}`} />
          <span>{isConnected ? 'Connected' : 'Disconnected'}</span>
        </div>
        
        {/* Supervision Indicator */}
        {isSupervisionActive && (
          <div className="flex items-center gap-1 text-coder1-cyan animate-pulse">
            <Eye className="w-4 h-4" />
            <span className="font-medium">Supervision Active</span>
          </div>
        )}
        
        {activeFile && (
          <div className="flex items-center gap-1">
            <GitBranch className="w-4 h-4" />
            <span>{activeFile}</span>
          </div>
        )}
        {lastCheckpoint && (
          <div className="flex items-center gap-1">
            <Check className="w-4 h-4 text-green-400" />
            <span>Checkpoint: {lastCheckpoint.toLocaleTimeString()}</span>
          </div>
        )}
      </div>

      {/* Center section - Action buttons */}
      <div className="flex items-center gap-2">
        {/* CheckPoint Button */}
        <button
          onClick={handleCheckpoint}
          disabled={isLoading === 'checkpoint'}
          className="flex items-center gap-1.5 px-4 py-1.5 text-sm font-medium text-text-secondary hover:text-text-primary rounded transition-all duration-200 disabled:opacity-50"
          style={{
            border: '1px solid #9333EA',
            backgroundColor: 'transparent',
          }}
          onMouseEnter={(e) => {
            if (isLoading !== 'checkpoint') {
              e.currentTarget.style.borderColor = glows.orange.borderHover;
              e.currentTarget.style.boxShadow = glows.orange.soft;
            }
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = '#9333EA';
            e.currentTarget.style.boxShadow = 'none';
          }}
          title="Save a checkpoint of your current work"
        >
          {isLoading === 'checkpoint' ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Save className="w-4 h-4" />
          )}
          <span>CheckPoint</span>
        </button>

        {/* TimeLine Button */}
        <button
          onClick={handleTimeline}
          disabled={isLoading === 'timeline'}
          className="flex items-center gap-1.5 px-4 py-1.5 text-sm font-medium text-text-secondary hover:text-text-primary rounded transition-all duration-200 disabled:opacity-50"
          style={{
            border: '1px solid #9333EA',
            backgroundColor: 'transparent',
          }}
          onMouseEnter={(e) => {
            if (isLoading !== 'timeline') {
              e.currentTarget.style.borderColor = glows.orange.borderHover;
              e.currentTarget.style.boxShadow = glows.orange.soft;
            }
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = '#9333EA';
            e.currentTarget.style.boxShadow = 'none';
          }}
          title="View timeline of changes"
        >
          {isLoading === 'timeline' ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Clock className="w-4 h-4" />
          )}
          <span>TimeLine</span>
        </button>

        {/* Export Button */}
        <button
          onClick={handleExport}
          disabled={isLoading === 'export'}
          className="flex items-center gap-1.5 px-4 py-1.5 text-sm font-medium text-text-secondary hover:text-text-primary rounded transition-all duration-200 disabled:opacity-50"
          style={{
            border: '1px solid #9333EA',
            backgroundColor: 'transparent',
          }}
          onMouseEnter={(e) => {
            if (isLoading !== 'export') {
              e.currentTarget.style.borderColor = glows.orange.borderHover;
              e.currentTarget.style.boxShadow = glows.orange.soft;
            }
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = '#9333EA';
            e.currentTarget.style.boxShadow = 'none';
          }}
          title="Export your project"
        >
          {isLoading === 'export' ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Download className="w-4 h-4" />
          )}
          <span>Export</span>
        </button>

        {/* Session Summary Button */}
        <button
          onClick={handleSessionSummary}
          disabled={isLoading === 'session'}
          className="flex items-center gap-1.5 px-4 py-1.5 text-sm font-medium text-text-secondary hover:text-text-primary rounded transition-all duration-200 disabled:opacity-50"
          style={{
            border: '1px solid #9333EA',
            backgroundColor: 'transparent',
          }}
          onMouseEnter={(e) => {
            if (isLoading !== 'session') {
              e.currentTarget.style.borderColor = glows.orange.borderHover;
              e.currentTarget.style.boxShadow = glows.orange.soft;
            }
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = '#9333EA';
            e.currentTarget.style.boxShadow = 'none';
          }}
          title="Generate AI session summary"
        >
          {isLoading === 'session' ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <FileText className="w-4 h-4" />
          )}
          <span>Session Summary</span>
        </button>

        {/* Docs Button */}
        <button
          onClick={handleDocs}
          className="flex items-center gap-1.5 px-4 py-1.5 text-sm font-medium text-text-secondary hover:text-text-primary rounded transition-all duration-200"
          style={{
            border: '1px solid #9333EA',
            backgroundColor: 'transparent',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.borderColor = glows.orange.borderHover;
            e.currentTarget.style.boxShadow = glows.orange.soft;
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.borderColor = '#9333EA';
            e.currentTarget.style.boxShadow = 'none';
          }}
          title="Open documentation"
        >
          <BookOpen className="w-4 h-4" />
          <span>Docs</span>
        </button>
      </div>

      {/* Right section - Additional info */}
      <div className="flex items-center gap-4 text-sm text-text-muted">
        <span>UTF-8</span>
        <span>TypeScript React</span>
        <span>Ln 1, Col 1</span>
      </div>
    </div>

    {/* Session Summary Modal */}
    {showSessionModal && (
      <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
        <div className="bg-bg-secondary border border-border-default rounded-lg w-full max-w-4xl max-h-[80vh] flex flex-col">
          {/* Modal Header */}
          <div className="flex items-center justify-between p-4 border-b border-border-default">
            <h2 className="text-lg font-semibold text-text-primary">Session Summary</h2>
            <button
              onClick={handleCloseModal}
              className="p-1 hover:bg-bg-primary rounded transition-colors"
            >
              <X className="w-5 h-5 text-text-muted" />
            </button>
          </div>

          {/* Modal Tabs */}
          <div className="flex gap-1 p-4 border-b border-border-default">
            <button
              onClick={() => setActiveTab('summary')}
              className={`px-4 py-2 rounded transition-all ${
                activeTab === 'summary' 
                  ? 'bg-orange-500/20 text-orange-400 border border-orange-500/50' 
                  : 'hover:bg-bg-primary text-text-muted'
              }`}
            >
              Summary
            </button>
            <button
              onClick={() => setActiveTab('insights')}
              className={`px-4 py-2 rounded transition-all ${
                activeTab === 'insights' 
                  ? 'bg-orange-500/20 text-orange-400 border border-orange-500/50' 
                  : 'hover:bg-bg-primary text-text-muted'
              }`}
            >
              Insights
            </button>
            <button
              onClick={() => setActiveTab('nextSteps')}
              className={`px-4 py-2 rounded transition-all ${
                activeTab === 'nextSteps' 
                  ? 'bg-orange-500/20 text-orange-400 border border-orange-500/50' 
                  : 'hover:bg-bg-primary text-text-muted'
              }`}
            >
              Next Steps
            </button>
          </div>

          {/* Modal Content */}
          <div className="flex-1 overflow-auto p-4">
            {isGenerating ? (
              <div className="flex flex-col items-center justify-center h-full gap-4">
                <Loader2 className="w-8 h-8 animate-spin text-orange-400" />
                <div className="text-center">
                  <p className="text-text-primary mb-2">Generating {currentStep}...</p>
                  <div className="w-64 h-2 bg-bg-primary rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-orange-400 transition-all duration-300"
                      style={{ width: `${progress}%` }}
                    />
                  </div>
                </div>
              </div>
            ) : summaryError ? (
              <div className="text-red-400">
                <p>Error generating summary: {summaryError}</p>
              </div>
            ) : (
              <div className="whitespace-pre-wrap text-text-secondary">
                {activeTab === 'summary' && (summary || 'No summary generated yet. Click regenerate to start.')}
                {activeTab === 'insights' && (insights || 'No insights generated yet.')}
                {activeTab === 'nextSteps' && (nextSteps || 'No next steps generated yet.')}
              </div>
            )}
          </div>

          {/* Modal Footer */}
          <div className="flex items-center justify-between gap-4 p-4 border-t border-border-default">
            <div className="flex items-center gap-2">
              {/* Export Format Selector */}
              <select
                value={exportFormat}
                onChange={(e) => setExportFormat(e.target.value as any)}
                className="px-3 py-1.5 bg-bg-primary border border-border-default rounded text-sm text-text-primary"
              >
                <option value="markdown">Markdown</option>
                <option value="json">JSON</option>
                <option value="html">HTML</option>
                <option value="all">All Formats</option>
              </select>
            </div>

            <div className="flex items-center gap-2">
              {/* Store in Docs Button */}
              <button
                onClick={handleStoreInDocs}
                disabled={!hasGenerated || isStoringInDocs}
                className="px-4 py-1.5 bg-green-500/20 text-green-400 border border-green-500/50 rounded hover:bg-green-500/30 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center gap-2"
              >
                {isStoringInDocs ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : storeSuccess ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Save className="w-4 h-4" />
                )}
                {storeSuccess ? 'Stored!' : 'Store in Docs'}
              </button>

              {/* Copy Button */}
              <button
                onClick={handleCopyToClipboard}
                disabled={!hasGenerated}
                className="px-4 py-1.5 bg-blue-500/20 text-blue-400 border border-blue-500/50 rounded hover:bg-blue-500/30 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center gap-2"
              >
                {copySuccess ? (
                  <>
                    <Check className="w-4 h-4" />
                    Copied!
                  </>
                ) : (
                  <>
                    <FileText className="w-4 h-4" />
                    Copy
                  </>
                )}
              </button>

              {/* Export Button */}
              <button
                onClick={handleExportSummary}
                disabled={!hasGenerated}
                className="px-4 py-1.5 bg-purple-500/20 text-purple-400 border border-purple-500/50 rounded hover:bg-purple-500/30 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                Export
              </button>

              {/* Regenerate Button */}
              <button
                onClick={() => handleSessionSummary()}
                disabled={isGenerating}
                className="px-4 py-1.5 bg-orange-500/20 text-orange-400 border border-orange-500/50 rounded hover:bg-orange-500/30 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                {isGenerating ? 'Generating...' : 'Regenerate'}
              </button>
            </div>
          </div>
        </div>
      </div>
    )}
    </>
  );
}