/**
 * Johnny5 Daemon Lifecycle Manager
 *
 * Manages the Johnny5/Johnny5 daemon as a macOS launchd service.
 * Handles installation, starting, stopping, and status checks.
 *
 * Key features:
 * - Detects node and Johnny5 paths dynamically
 * - Creates wrapper script that sources .env for environment variables
 * - Uses launchd for auto-start on login (no sudo required)
 * - Handles reinstallation gracefully
 */

const { execSync, exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

// Constants
const PLIST_LABEL = 'com.coder1.johnny5';
const PLIST_FILENAME = `${PLIST_LABEL}.plist`;
const LAUNCH_AGENTS_DIR = path.join(os.homedir(), 'Library', 'LaunchAgents');
const PLIST_PATH = path.join(LAUNCH_AGENTS_DIR, PLIST_FILENAME);
const CODER1_DIR = path.join(os.homedir(), '.coder1');
const CODER1_BIN_DIR = path.join(CODER1_DIR, 'bin');
const WRAPPER_SCRIPT_PATH = path.join(CODER1_BIN_DIR, 'johnny5-start.sh');
const JOHNNY5_PATH_CONFIG = path.join(CODER1_DIR, 'johnny5-path');
const LOG_FILE = '/tmp/johnny5.log';
const ERROR_LOG_FILE = '/tmp/johnny5.error.log';

/**
 * Detect the node executable path
 * @returns {string} Full path to node
 */
function detectNodePath() {
  try {
    const nodePath = execSync('which node', { encoding: 'utf-8' }).trim();
    if (nodePath && fs.existsSync(nodePath)) {
      return nodePath;
    }
  } catch (e) {
    // which failed
  }

  // Fallback paths
  const fallbacks = [
    '/usr/local/bin/node',
    '/opt/homebrew/bin/node',
    path.join(os.homedir(), '.nvm/versions/node/*/bin/node'), // Will need glob
    '/usr/bin/node',
  ];

  for (const p of fallbacks) {
    if (fs.existsSync(p)) {
      return p;
    }
  }

  throw new Error('Node.js not found. Please ensure node is installed and in your PATH.');
}

/**
 * Read the stored Johnny5 path from config file
 * @returns {string|null}
 */
function readStoredJohnny5Path() {
  if (fs.existsSync(JOHNNY5_PATH_CONFIG)) {
    try {
      return fs.readFileSync(JOHNNY5_PATH_CONFIG, 'utf-8').trim();
    } catch (e) {
      return null;
    }
  }
  return null;
}

/**
 * Store Johnny5 path to config file
 * @param {string} p Path to store
 */
function storeJohnny5Path(p) {
  ensureDirectories();
  fs.writeFileSync(JOHNNY5_PATH_CONFIG, p, 'utf-8');
}

/**
 * Detect the Johnny5/Johnny5 installation path
 * @returns {string|null} Path to Johnny5 directory, or null if not found
 */
function detectJohnny5Path() {
  // Priority order: env var > config file > default location
  const candidates = [
    process.env.JOHNNY5_PATH,
    readStoredJohnny5Path(),
    path.join(os.homedir(), 'johnny5', 'johnny5'),
    path.join(os.homedir(), 'johnny5'),
    path.join(os.homedir(), '.johnny5'),
  ];

  for (const p of candidates) {
    if (p && isValidJohnny5Path(p)) {
      return p;
    }
  }

  return null;
}

/**
 * Validate that a path contains a valid Johnny5 installation
 * @param {string} p Path to check
 * @returns {boolean}
 */
function isValidJohnny5Path(p) {
  if (!p) return false;
  try {
    const cliPath = path.join(p, 'dist', 'cli.js');
    const packagePath = path.join(p, 'package.json');
    return fs.existsSync(cliPath) && fs.existsSync(packagePath);
  } catch (e) {
    return false;
  }
}

/**
 * Ensure required directories exist
 */
function ensureDirectories() {
  if (!fs.existsSync(CODER1_DIR)) {
    fs.mkdirSync(CODER1_DIR, { recursive: true });
  }
  if (!fs.existsSync(CODER1_BIN_DIR)) {
    fs.mkdirSync(CODER1_BIN_DIR, { recursive: true });
  }
  if (!fs.existsSync(LAUNCH_AGENTS_DIR)) {
    fs.mkdirSync(LAUNCH_AGENTS_DIR, { recursive: true });
  }
}

/**
 * Generate the wrapper shell script that sources .env before starting the daemon
 * @param {string} johnny5Path Path to Johnny5 installation
 * @param {string} nodePath Full path to node executable
 * @returns {string} Shell script content
 */
function generateWrapperScript(johnny5Path, nodePath) {
  // Note: We embed the node path at install time because launchd has a minimal PATH
  return `#!/bin/bash
# Johnny5 Daemon Wrapper Script
# Generated by Coder1 Bridge CLI
# This script sources .env before starting the daemon

# Allow JOHNNY5_PATH override, default to stored path
JOHNNY5_PATH="\${JOHNNY5_PATH:-${johnny5Path}}"

# Node path (detected at install time)
NODE_PATH="${nodePath}"

# Change to Johnny5 directory
cd "$JOHNNY5_PATH" || exit 1

# Source environment variables from .env if it exists
if [ -f .env ]; then
  set -a
  source .env
  set +a
fi

# Execute the Johnny5 daemon
# Using 'exec' replaces the shell process with node, ensuring proper signal handling
exec "$NODE_PATH" dist/cli.js gateway
`;
}

/**
 * Generate the launchd plist XML
 * @param {string} wrapperPath Full path to the wrapper script
 * @returns {string} Plist XML content
 */
function generatePlist(wrapperPath) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${wrapperPath}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>StandardOutPath</key>
    <string>${LOG_FILE}</string>
    <key>StandardErrorPath</key>
    <string>${ERROR_LOG_FILE}</string>
    <key>ThrottleInterval</key>
    <integer>5</integer>
</dict>
</plist>
`;
}

/**
 * Check if the daemon is installed (either our plist or Johnny5's plist exists)
 * @returns {boolean}
 */
function isInstalled() {
  // Check our plist
  if (fs.existsSync(PLIST_PATH)) return true;
  // Check Johnny5's plist
  const johnny5Plist = path.join(LAUNCH_AGENTS_DIR, 'com.johnny5.agent.plist');
  if (fs.existsSync(johnny5Plist)) return true;
  return false;
}

/**
 * Check if the daemon is loaded in launchd
 * @returns {boolean}
 */
function isLoaded() {
  try {
    // Check for either our service or Johnny5's service
    const result = execSync(`launchctl list 2>/dev/null | grep -E '(${PLIST_LABEL}|com.johnny5)'`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return result.length > 0;
  } catch (e) {
    return false;
  }
}

/**
 * Check if the daemon is running (process exists and port is listening)
 * @returns {{running: boolean, pid?: number, port?: number}}
 */
function isRunning() {
  try {
    // Check if port 55413 is listening
    const lsofResult = execSync('lsof -i :55413 -sTCP:LISTEN -t 2>/dev/null', {
      encoding: 'utf-8',
    }).trim();

    if (lsofResult) {
      const pid = parseInt(lsofResult.split('\n')[0], 10);
      return { running: true, pid, port: 55413 };
    }
  } catch (e) {
    // lsof failed or no process found
  }

  return { running: false };
}

/**
 * Install the Johnny5 daemon as a launchd service
 * Delegates to Johnny5's built-in daemon management
 * @returns {{success: boolean, message: string, path?: string}}
 */
function install() {
  console.log('\x1b[34m🔧 Installing Johnny5 daemon...\x1b[0m');

  // Step 1: Detect Johnny5 path
  const johnny5Path = detectJohnny5Path();
  if (!johnny5Path) {
    const errorMsg = `Johnny5 not found.

Checked locations:
- $JOHNNY5_PATH environment variable
- ${JOHNNY5_PATH_CONFIG}
- ${path.join(os.homedir(), 'johnny5', 'johnny5')}
- ${path.join(os.homedir(), 'johnny5')}

To fix: Set JOHNNY5_PATH environment variable to your Johnny5 installation directory.`;
    console.log('\x1b[31m❌ ' + errorMsg + '\x1b[0m');
    return { success: false, message: errorMsg };
  }
  console.log(`\x1b[90m   Found Johnny5 at: ${johnny5Path}\x1b[0m`);

  // Step 2: Store johnny5 path for future use
  storeJohnny5Path(johnny5Path);

  // Step 3: Ensure our directories exist
  ensureDirectories();

  // Step 4: Use Johnny5's built-in daemon installer
  // This is cleaner than creating our own launchd plist since Johnny5
  // already knows how to manage itself
  console.log('\x1b[90m   Installing daemon via Johnny5 CLI...\x1b[0m');
  try {
    const result = execSync(`cd "${johnny5Path}" && node dist/cli.js daemon install 2>&1`, {
      encoding: 'utf-8',
      timeout: 30000,
    });
    console.log('\x1b[90m' + result.split('\n').map(l => '   ' + l).join('\n') + '\x1b[0m');
  } catch (e) {
    // Installation might "fail" but still succeed - check status
    console.log('\x1b[90m   Checking installation status...\x1b[0m');
  }

  // Step 5: Start the daemon
  console.log('\x1b[90m   Starting daemon...\x1b[0m');
  try {
    execSync(`cd "${johnny5Path}" && node dist/cli.js daemon start 2>&1`, {
      encoding: 'utf-8',
      timeout: 30000,
    });
  } catch (e) {
    // Ignore start errors - check status instead
  }

  // Step 6: Wait and verify daemon is running
  console.log('\x1b[90m   Waiting for daemon to start...\x1b[0m');
  let attempts = 0;
  const maxAttempts = 10;

  while (attempts < maxAttempts) {
    const runStatus = isRunning();
    if (runStatus.running) {
      console.log(`\x1b[32m✅ Johnny5 daemon installed and running (PID: ${runStatus.pid})\x1b[0m`);
      console.log(`\x1b[90m   Gateway: http://localhost:55413\x1b[0m`);
      console.log(`\x1b[90m   Logs: johnny5 daemon logs\x1b[0m`);
      return {
        success: true,
        message: 'Johnny5 daemon installed successfully',
        path: johnny5Path,
        pid: runStatus.pid,
      };
    }
    // Wait 500ms between checks
    execSync('sleep 0.5');
    attempts++;
  }

  // Daemon didn't start - get status from Johnny5
  let statusOutput = '';
  try {
    statusOutput = execSync(`cd "${johnny5Path}" && node dist/cli.js daemon status 2>&1`, {
      encoding: 'utf-8',
    });
  } catch (e) {
    statusOutput = e.message;
  }

  const errorMsg = `Daemon installed but failed to start within ${maxAttempts * 0.5}s.

Johnny5 daemon status:
${statusOutput}

Try manually: cd ${johnny5Path} && node dist/cli.js daemon start`;
  console.log('\x1b[33m⚠️  ' + errorMsg + '\x1b[0m');
  return { success: false, message: errorMsg };
}

/**
 * Uninstall the Johnny5 daemon
 * @returns {{success: boolean, message: string}}
 */
function uninstall() {
  console.log('\x1b[34m🗑️  Uninstalling Johnny5 daemon...\x1b[0m');

  const johnny5Path = detectJohnny5Path();
  if (!johnny5Path) {
    console.log('\x1b[33m⚠️  Johnny5 not found, nothing to uninstall\x1b[0m');
    return { success: true, message: 'Nothing to uninstall' };
  }

  // Use Johnny5's daemon uninstall
  try {
    const result = execSync(`cd "${johnny5Path}" && node dist/cli.js daemon uninstall 2>&1`, {
      encoding: 'utf-8',
      timeout: 30000,
    });
    console.log('\x1b[90m' + result.split('\n').map(l => '   ' + l).join('\n') + '\x1b[0m');
  } catch (e) {
    // Ignore errors
  }

  // Also clean up our files if they exist
  if (fs.existsSync(PLIST_PATH)) {
    try {
      execSync(`launchctl unload "${PLIST_PATH}" 2>/dev/null`, { stdio: 'ignore' });
    } catch (e) {}
    fs.unlinkSync(PLIST_PATH);
    console.log(`\x1b[90m   Removed: ${PLIST_PATH}\x1b[0m`);
  }

  if (fs.existsSync(WRAPPER_SCRIPT_PATH)) {
    fs.unlinkSync(WRAPPER_SCRIPT_PATH);
    console.log(`\x1b[90m   Removed: ${WRAPPER_SCRIPT_PATH}\x1b[0m`);
  }

  console.log('\x1b[32m✅ Johnny5 daemon uninstalled\x1b[0m');
  return { success: true, message: 'Johnny5 daemon uninstalled successfully' };
}

/**
 * Start the Johnny5 daemon (if installed but not running)
 * @returns {{success: boolean, message: string}}
 */
function start() {
  console.log('\x1b[34m▶️  Starting Johnny5 daemon...\x1b[0m');

  const johnny5Path = detectJohnny5Path();
  if (!johnny5Path) {
    console.log('\x1b[31m❌ Johnny5 not found. Run: coder1-bridge johnny5 install\x1b[0m');
    return { success: false, message: 'Johnny5 not found' };
  }

  const runStatus = isRunning();
  if (runStatus.running) {
    console.log(`\x1b[33m⚠️  Johnny5 daemon is already running (PID: ${runStatus.pid})\x1b[0m`);
    return { success: true, message: 'Already running', pid: runStatus.pid };
  }

  // Start via Johnny5 CLI
  try {
    const result = execSync(`cd "${johnny5Path}" && node dist/cli.js daemon start 2>&1`, {
      encoding: 'utf-8',
      timeout: 30000,
    });
    console.log('\x1b[90m' + result.split('\n').map(l => '   ' + l).join('\n') + '\x1b[0m');
  } catch (e) {
    // Ignore - check status instead
  }

  // Wait for startup
  execSync('sleep 2');
  const newStatus = isRunning();
  if (newStatus.running) {
    console.log(`\x1b[32m✅ Johnny5 daemon started (PID: ${newStatus.pid})\x1b[0m`);
    return { success: true, message: 'Started', pid: newStatus.pid };
  }

  console.log('\x1b[31m❌ Daemon failed to start. Try: cd ' + johnny5Path + ' && node dist/cli.js daemon logs\x1b[0m');
  return { success: false, message: 'Failed to start' };
}

/**
 * Stop the Johnny5 daemon
 * @returns {{success: boolean, message: string}}
 */
function stop() {
  console.log('\x1b[34m⏹️  Stopping Johnny5 daemon...\x1b[0m');

  const runStatus = isRunning();
  if (!runStatus.running) {
    console.log('\x1b[33m⚠️  Johnny5 daemon is not running\x1b[0m');
    return { success: true, message: 'Not running' };
  }

  const johnny5Path = detectJohnny5Path();
  if (johnny5Path) {
    // Stop via Johnny5 CLI
    try {
      const result = execSync(`cd "${johnny5Path}" && node dist/cli.js daemon stop 2>&1`, {
        encoding: 'utf-8',
        timeout: 30000,
      });
      console.log('\x1b[90m' + result.split('\n').map(l => '   ' + l).join('\n') + '\x1b[0m');
    } catch (e) {
      // Ignore - check status
    }
  }

  // Verify stopped
  execSync('sleep 1');
  const newStatus = isRunning();
  if (!newStatus.running) {
    console.log('\x1b[32m✅ Johnny5 daemon stopped\x1b[0m');
    return { success: true, message: 'Stopped' };
  }

  // Fallback: kill process directly
  if (runStatus.pid) {
    try {
      process.kill(runStatus.pid, 'SIGTERM');
      console.log('\x1b[32m✅ Johnny5 daemon stopped (via SIGTERM)\x1b[0m');
      return { success: true, message: 'Stopped via SIGTERM' };
    } catch (e2) {
      // Ignore kill errors
    }
  }

  console.log('\x1b[31m❌ Failed to stop daemon\x1b[0m');
  return { success: false, message: 'Failed to stop' };
}

/**
 * Get the status of the Johnny5 daemon
 * @returns {{installed: boolean, loaded: boolean, running: boolean, pid?: number, port?: number, path?: string}}
 */
function status() {
  const installed = isInstalled();
  const loaded = isLoaded();
  const runningStatus = isRunning();
  const johnny5Path = detectJohnny5Path();

  console.log('\n\x1b[34m📊 Johnny5 Daemon Status\x1b[0m');
  console.log('\x1b[90m' + '─'.repeat(40) + '\x1b[0m');

  // Installation status
  if (installed) {
    console.log(`\x1b[32m✅ Installed\x1b[0m: ${PLIST_PATH}`);
  } else {
    console.log('\x1b[33m○  Not installed\x1b[0m');
  }

  // Loaded in launchd
  if (loaded) {
    console.log('\x1b[32m✅ Loaded\x1b[0m: Service registered with launchd');
  } else if (installed) {
    console.log('\x1b[33m○  Not loaded\x1b[0m: Service not registered with launchd');
  }

  // Running status
  if (runningStatus.running) {
    console.log(`\x1b[32m✅ Running\x1b[0m: PID ${runningStatus.pid}, Port ${runningStatus.port}`);
  } else {
    console.log('\x1b[33m○  Not running\x1b[0m');
  }

  // Johnny5 path
  if (johnny5Path) {
    console.log(`\x1b[90m   Johnny5 path: ${johnny5Path}\x1b[0m`);
  } else {
    console.log('\x1b[33m   Johnny5 path: Not found\x1b[0m');
  }

  // Log locations
  console.log(`\x1b[90m   Stdout log: ${LOG_FILE}\x1b[0m`);
  console.log(`\x1b[90m   Stderr log: ${ERROR_LOG_FILE}\x1b[0m`);

  console.log('\x1b[90m' + '─'.repeat(40) + '\x1b[0m\n');

  return {
    installed,
    loaded,
    running: runningStatus.running,
    pid: runningStatus.pid,
    port: runningStatus.port,
    path: johnny5Path,
  };
}

// Export functions for CLI and API usage
module.exports = {
  install,
  uninstall,
  start,
  stop,
  status,
  isInstalled,
  isLoaded,
  isRunning,
  detectJohnny5Path,
  detectNodePath,
  // Export constants for testing
  PLIST_PATH,
  WRAPPER_SCRIPT_PATH,
  LOG_FILE,
  ERROR_LOG_FILE,
};
