/**
 * Memory API Routes - Main CRUD operations
 * GET /api/memories - List memories with filtering
 * POST /api/memories - Create new memory
 */

import { NextRequest, NextResponse } from 'next/server';
import { memoryDb } from '@/lib/db/memory-database';

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    
    const options = {
      limit: parseInt(searchParams.get('limit') || '50'),
      offset: parseInt(searchParams.get('offset') || '0'),
      type: searchParams.get('type') as any,
      minConfidence: searchParams.get('minConfidence') 
        ? parseFloat(searchParams.get('minConfidence')!)
        : undefined,
      starred: searchParams.get('starred') === 'true',
      sessionId: searchParams.get('sessionId') || undefined,
      checkpointId: searchParams.get('checkpointId') || undefined,
      orderBy: (searchParams.get('orderBy') || 'created_at') as any,
      orderDirection: (searchParams.get('orderDirection') || 'DESC') as any,
    };

    const result = memoryDb.listMemories(options);

    return NextResponse.json({
      success: true,
      data: result.memories,
      pagination: {
        total: result.total,
        limit: options.limit,
        offset: options.offset,
        hasMore: options.offset + options.limit < result.total
      }
    });
  } catch (error) {
    console.error('Error listing memories:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to list memories' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    // Validate required fields
    if (!body.title || !body.type) {
      return NextResponse.json(
        { success: false, error: 'Title and type are required' },
        { status: 400 }
      );
    }

    // Set defaults
    const memoryData = {
      title: body.title,
      description: body.description || '',
      type: body.type,
      confidence: body.confidence || 0.5,
      tags: body.tags || [],
      context: body.context || { files: [], commands: [] },
      checkpointId: body.checkpointId,
      sessionId: body.sessionId,
      autoGenerated: body.autoGenerated || false,
      templateType: body.templateType || 'default',
      starred: body.starred || false,
    };

    const memory = memoryDb.createMemory(memoryData);

    // Add events if provided
    if (body.events && Array.isArray(body.events)) {
      for (const event of body.events) {
        memoryDb.addMemoryEvent({
          memoryId: memory.id!,
          eventType: event.eventType || event.type,
          eventData: event.eventData || event,
          confidence: event.confidence || 0.5,
          files: event.files || [],
          commands: event.commands || [],
          errors: event.errors || [],
        });
      }
    }

    return NextResponse.json({
      success: true,
      data: memory
    });
  } catch (error) {
    console.error('Error creating memory:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to create memory' },
      { status: 500 }
    );
  }
}