const fs = require('fs').promises;
const path = require('path');

class AttributionTracker {
  constructor() {
    this.dataDir = path.join(__dirname, '../data');
    this.attributionDb = path.join(this.dataDir, 'attribution-data.json');
    
    this.attributionFooter = `\n---\n*🤖 Built with [Coder1](https://coder1.dev) - The AI-First IDE*  \n*Try it free: [coder1.dev](https://coder1.dev)*\n`;
  }

  async initialize() {
    await fs.mkdir(this.dataDir, { recursive: true });
    
    try {
      const data = await fs.readFile(this.attributionDb, 'utf8');
      this.attributions = JSON.parse(data);
    } catch (error) {
      this.attributions = {
        total_attributions: 0,
        by_type: {},
        by_date: {},
        clicks: []
      };
    }
  }

  addAttributionToContent(content, contentType = 'blog') {
    const attributions = {
      'blog': this.attributionFooter,
      'youtube': `\n---\n🤖 Script generated with Coder1\n💻 Try Coder1: https://coder1.dev\n⭐ Star on GitHub: github.com/MichaelrKraft/coder1-ide\n`,
      'case_study': this.attributionFooter,
      'documentation': `\n---\n*📚 Documentation auto-generated by Coder1 Docs Generator*\n`,
      'code': `// Built with Coder1 - https://coder1.dev\n`,
      'session_export': `\n\n---\n**Built with Coder1 IDE** in record time.\n\nReady to supercharge your development? Try Coder1 free at [coder1.dev](https://coder1.dev)\n`
    };

    const attribution = attributions[contentType] || this.attributionFooter;
    
    if (content.includes(attribution)) {
      return content;
    }

    return content + attribution;
  }

  generateShareableLink(contentId, contentType, source = 'direct') {
    const baseUrl = 'https://coder1.dev';
    
    const params = new URLSearchParams({
      ref: source,
      content: contentId,
      type: contentType
    });

    return `${baseUrl}/?${params.toString()}`;
  }

  createSocialShareText(title, contentType) {
    const templates = {
      'blog': `📝 Just published: ${title}\n\nBuilt with @Coder1IDE - the AI-first development environment.\n\nRead more:`,
      'youtube': `🎬 New tutorial: ${title}\n\nWatch how we build this in under 15 minutes with @Coder1IDE.\n\nWatch now:`,
      'case_study': `💡 Case study: ${title}\n\nSee how developers are shipping faster with @Coder1IDE.\n\nRead the full story:`,
      'project': `🚀 Just shipped: ${title}\n\nBuilt with @Coder1IDE in record time. AI-assisted development is the future.\n\nTry it free:`
    };

    return templates[contentType] || `Check out: ${title}\n\nBuilt with Coder1:`;
  }

  async trackAttribution(contentId, contentType, metadata = {}) {
    await this.initialize();

    const attribution = {
      id: contentId,
      type: contentType,
      created_at: new Date().toISOString(),
      metadata
    };

    this.attributions.total_attributions++;
    
    if (!this.attributions.by_type[contentType]) {
      this.attributions.by_type[contentType] = 0;
    }
    this.attributions.by_type[contentType]++;

    const date = new Date().toISOString().split('T')[0];
    if (!this.attributions.by_date[date]) {
      this.attributions.by_date[date] = 0;
    }
    this.attributions.by_date[date]++;

    await this.saveDatabase();

    return attribution;
  }

  async trackClick(shareableLink, source = 'unknown', metadata = {}) {
    await this.initialize();

    const click = {
      link: shareableLink,
      source,
      clicked_at: new Date().toISOString(),
      metadata
    };

    this.attributions.clicks.push(click);
    await this.saveDatabase();

    return click;
  }

  async getStats(days = 30) {
    await this.initialize();

    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - days);
    const cutoffStr = cutoffDate.toISOString().split('T')[0];

    const recentClicks = this.attributions.clicks.filter(c => 
      c.clicked_at >= cutoffStr
    );

    const recentByDate = Object.entries(this.attributions.by_date)
      .filter(([date]) => date >= cutoffStr)
      .reduce((acc, [date, count]) => {
        acc[date] = count;
        return acc;
      }, {});

    return {
      total_attributions: this.attributions.total_attributions,
      attributions_by_type: this.attributions.by_type,
      recent_attributions: recentByDate,
      total_clicks: this.attributions.clicks.length,
      recent_clicks: recentClicks.length,
      click_through_rate: this.calculateCTR(recentByDate, recentClicks.length),
      top_sources: this.getTopSources(recentClicks)
    };
  }

  calculateCTR(attributions, clicks) {
    const totalAttributions = Object.values(attributions).reduce((sum, count) => sum + count, 0);
    if (totalAttributions === 0) return 0;
    return ((clicks / totalAttributions) * 100).toFixed(2) + '%';
  }

  getTopSources(clicks) {
    const sources = {};
    clicks.forEach(click => {
      sources[click.source] = (sources[click.source] || 0) + 1;
    });

    return Object.entries(sources)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([source, count]) => ({ source, clicks: count }));
  }

  async saveDatabase() {
    await fs.writeFile(
      this.attributionDb,
      JSON.stringify(this.attributions, null, 2)
    );
  }

  generateAttributionReport() {
    return {
      summary: {
        total_content_pieces: this.attributions.total_attributions,
        total_clicks: this.attributions.clicks.length,
        types: this.attributions.by_type
      },
      recent_activity: Object.entries(this.attributions.by_date)
        .sort(([a], [b]) => b.localeCompare(a))
        .slice(0, 7)
        .map(([date, count]) => ({ date, attributions: count })),
      top_performing: this.getTopSources(this.attributions.clicks)
    };
  }
}

async function main() {
  const tracker = new AttributionTracker();
  
  try {
    console.log('📊 Attribution Tracker\n');
    
    console.log('Example: Adding attribution to blog post...');
    const blogPost = `# My Amazing Blog Post\n\nThis is content...`;
    const withAttribution = tracker.addAttributionToContent(blogPost, 'blog');
    console.log('\nResult:');
    console.log(withAttribution);
    
    console.log('\n' + '='.repeat(60));
    console.log('Example: Creating shareable link...');
    const link = tracker.generateShareableLink('blog-123', 'blog', 'twitter');
    console.log(`Link: ${link}`);
    
    console.log('\n' + '='.repeat(60));
    console.log('Example: Social share text...');
    const shareText = tracker.createSocialShareText('Building APIs with Coder1', 'blog');
    console.log(shareText);
    console.log(link);
    
    console.log('\n' + '='.repeat(60));
    console.log('Getting attribution stats...\n');
    const stats = await tracker.getStats(30);
    
    console.log('📈 ATTRIBUTION STATISTICS (Last 30 Days)');
    console.log('='.repeat(60));
    console.log(`Total Attributions: ${stats.total_attributions}`);
    console.log(`Total Clicks: ${stats.total_clicks}`);
    console.log(`Click-Through Rate: ${stats.click_through_rate}`);
    console.log('\nBy Type:');
    Object.entries(stats.attributions_by_type).forEach(([type, count]) => {
      console.log(`  ${type}: ${count}`);
    });
    
    if (stats.top_sources.length > 0) {
      console.log('\nTop Sources:');
      stats.top_sources.forEach((source, i) => {
        console.log(`  ${i + 1}. ${source.source}: ${source.clicks} clicks`);
      });
    }
    console.log('='.repeat(60));
    
  } catch (error) {
    console.error('❌ Error:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = AttributionTracker;
