#!/usr/bin/env node
/**
 * Direct Mode Handler - Posts directly to GitHub without email approval
 * Used by GitHub Actions for immediate responses
 */

require('dotenv').config({ path: '../.env.local' });

const ClaudeAPI = require('./lib/claude-api');
const GitHubDirectPoster = require('./github-direct-poster');

async function handleDirectMode() {
  console.log('🚀 Running in DIRECT MODE - No email approval needed');
  
  // Get issue details from environment (set by GitHub Actions)
  const issueNumber = process.env.ISSUE_NUMBER;
  const issueTitle = process.env.ISSUE_TITLE;
  const issueBody = process.env.ISSUE_BODY;
  const issueAuthor = process.env.ISSUE_AUTHOR;
  
  if (!issueNumber) {
    console.error('❌ No issue number provided');
    process.exit(1);
  }
  
  console.log(`📝 Processing issue #${issueNumber}: ${issueTitle}`);
  
  try {
    // Initialize services
    const claude = new ClaudeAPI();
    await claude.initialize?.();  // If there's an initialize method
    
    const poster = new GitHubDirectPoster();
    
    // Generate response using Claude
    const issue = {
      number: issueNumber,
      title: issueTitle,
      body: issueBody,
      user: { login: issueAuthor }
    };
    
    console.log('🤖 Generating response with Claude...');
    const response = await claude.generateIssueResponse(issue);
    
    // Add footer to response
    const finalResponse = `${response.text || response}

---
*🤖 This response was generated by Coder1's AI assistant powered by Claude. [Learn more about our autonomous agents](https://github.com/${process.env.GITHUB_OWNER || 'MichaelrKraft'}/${process.env.GITHUB_REPO || 'coder1-ide'}/blob/master/agents/README.md)*`;
    
    // Post directly to GitHub
    console.log('📤 Posting response to GitHub...');
    await poster.postComment(issueNumber, finalResponse);
    
    // Add labels if suggested
    if (response.metadata?.labels) {
      await poster.addLabels(issueNumber, response.metadata.labels);
    }
    
    console.log('✅ Successfully handled issue in direct mode!');
    
    // Log cost
    if (response.cost) {
      console.log(`💰 Cost: $${response.cost.toFixed(4)}`);
    }
    
  } catch (error) {
    console.error('❌ Error in direct mode:', error);
    
    // Post error message to issue
    try {
      const poster = new GitHubDirectPoster();
      const errorMessage = `Thank you for your issue, @${issueAuthor}! 

I encountered an error while processing your request, but a human maintainer has been notified and will respond soon.

*Error: ${error.message || 'Unknown error occurred'}*`;
      
      await poster.postComment(issueNumber, errorMessage);
    } catch (postError) {
      console.error('Failed to post error message:', postError);
    }
    
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  handleDirectMode();
}

module.exports = handleDirectMode;