/**
 * FossilRecordService — auto-documents significant Claude sessions as vault notes.
 *
 * Triggered by session completion events. Writes to Sessions/ folder in vault.
 * All vault writes are via the vault API — never direct file system access.
 */

import { featureFlags } from '@/config/feature-flags';

interface SessionSummary {
  sessionId: string;
  topic: string;
  startedAt: number;
  endedAt: number;
  messageCount: number;
  filesModified: string[];
  decisions: string[];
  keyPoints: string[];
  checkpointId?: string;
}

export class FossilRecordService {
  private static readonly THRESHOLD_MESSAGES = 5;
  private static readonly THRESHOLD_DURATION_MS = 5 * 60 * 1000; // 5 minutes

  static isSignificant(session: {
    messageCount: number;
    durationMs: number;
    filesModified: string[];
  }): boolean {
    return (
      session.messageCount >= this.THRESHOLD_MESSAGES ||
      session.durationMs >= this.THRESHOLD_DURATION_MS ||
      session.filesModified.length > 0
    );
  }

  static async recordSession(summary: SessionSummary): Promise<string | null> {
    if (!featureFlags.isEnabled('VAULT_ENABLED')) return null;

    try {
      const date = new Date(summary.startedAt).toISOString().split('T')[0];
      const slug = summary.topic
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
        .slice(0, 40);

      const notePath = `Sessions/${date}-${slug}.md`;
      const content = this.formatSessionNote(summary);

      const response = await fetch('/api/vault', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          path: notePath,
          title: `${date}: ${summary.topic}`,
          content,
          frontmatter: {
            session_id: summary.sessionId,
            date,
            duration_minutes: Math.round((summary.endedAt - summary.startedAt) / 60000),
            message_count: summary.messageCount,
            checkpoint: summary.checkpointId || null,
            tags: ['session', 'fossil-record'],
          },
        }),
      });

      if (!response.ok) return null;
      const note = await response.json();
      return note.path;
    } catch (err) {
      console.error('[FossilRecordService] Failed to record session:', err);
      return null;
    }
  }

  private static formatSessionNote(summary: SessionSummary): string {
    const date = new Date(summary.startedAt).toLocaleDateString();
    const duration = Math.round((summary.endedAt - summary.startedAt) / 60000);

    const sections: string[] = [
      `## Summary`,
      ``,
      summary.keyPoints.length > 0
        ? summary.keyPoints.map(p => `- ${p}`).join('\n')
        : `Session with ${summary.messageCount} messages over ${duration} minutes.`,
      ``,
    ];

    if (summary.decisions.length > 0) {
      sections.push(`## Decisions Made`, ``);
      for (const decision of summary.decisions) {
        sections.push(`- ${decision}`);
      }
      sections.push(``);
    }

    if (summary.filesModified.length > 0) {
      sections.push(`## Files Modified`, ``);
      for (const file of summary.filesModified) {
        sections.push(`- \`${file}\``);
      }
      sections.push(``);
    }

    if (summary.checkpointId) {
      sections.push(`## Checkpoint`, ``, `[Replay session](checkpoint://${summary.checkpointId})`, ``);
    }

    sections.push(
      `---`,
      `*Auto-generated by Fossil Record — ${new Date(summary.endedAt).toLocaleString()}*`
    );

    return sections.join('\n');
  }
}
