import type { TikTokVideo, TikTokProfile } from './types'

/**
 * Mock TikTok video data for development without Apify
 * Includes 25 diverse influencers across different niches and tiers
 */
export const mockTikTokVideos: TikTokVideo[] = [
  // Fitness Influencers
  {
    id: 'mock_001',
    text: 'New morning workout routine that changed my life! #fitness #workout #gym #motivation #fitfam',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 3,
    authorMeta: {
      id: 'user_001',
      name: 'fitnessmaven',
      nickName: 'Sarah Fitness',
      verified: true,
      signature: 'Certified PT | Transform your body | Daily workouts | collab@sarahfitness.com',
      avatar: 'https://placehold.co/150x150/FF6B6B/white?text=SF',
      following: 450,
      fans: 1250000,
      heart: 45000000,
      video: 342,
      digg: 5000,
    },
    musicMeta: {
      musicId: 'music_001',
      musicName: 'Workout Beats',
      musicAuthor: 'Various Artists',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 30,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 45,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 285000,
      shareCount: 12000,
      commentCount: 8500,
      playCount: 5200000,
      collectCount: 45000,
    },
    hashtags: [
      { id: 'h1', name: 'fitness' },
      { id: 'h2', name: 'workout' },
      { id: 'h3', name: 'gym' },
      { id: 'h4', name: 'motivation' },
      { id: 'h5', name: 'fitfam' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@fitnessmaven/video/mock_001',
  },
  {
    id: 'mock_002',
    text: 'Home workout no equipment needed! Perfect for beginners #homeworkout #fitness #noequipment',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 5,
    authorMeta: {
      id: 'user_002',
      name: 'homegymhero',
      nickName: 'Mike Home Gym',
      verified: false,
      signature: 'No gym? No problem! Home workouts for everyone',
      avatar: 'https://placehold.co/150x150/4ECDC4/white?text=MH',
      following: 320,
      fans: 85000,
      heart: 2100000,
      video: 156,
      digg: 3200,
    },
    musicMeta: {
      musicId: 'music_002',
      musicName: 'Pump It Up',
      musicAuthor: 'DJ Fitness',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 25,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 60,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 45000,
      shareCount: 8500,
      commentCount: 3200,
      playCount: 890000,
      collectCount: 12000,
    },
    hashtags: [
      { id: 'h1', name: 'homeworkout' },
      { id: 'h2', name: 'fitness' },
      { id: 'h3', name: 'noequipment' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@homegymhero/video/mock_002',
  },
  // Beauty Influencers
  {
    id: 'mock_003',
    text: 'Everyday makeup tutorial in under 5 minutes! #beauty #makeup #tutorial #grwm #skincare',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 2,
    authorMeta: {
      id: 'user_003',
      name: 'beautybyella',
      nickName: 'Ella Beauty',
      verified: true,
      signature: 'Beauty tips & tutorials | Cruelty-free only | business@ellabeauty.co',
      avatar: 'https://placehold.co/150x150/FF85A2/white?text=EB',
      following: 280,
      fans: 3200000,
      heart: 89000000,
      video: 567,
      digg: 12000,
    },
    musicMeta: {
      musicId: 'music_003',
      musicName: 'Soft Glam',
      musicAuthor: 'Beauty Sounds',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 40,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 55,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 520000,
      shareCount: 35000,
      commentCount: 18000,
      playCount: 9500000,
      collectCount: 85000,
    },
    hashtags: [
      { id: 'h1', name: 'beauty' },
      { id: 'h2', name: 'makeup' },
      { id: 'h3', name: 'tutorial' },
      { id: 'h4', name: 'grwm' },
      { id: 'h5', name: 'skincare' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@beautybyella/video/mock_003',
  },
  {
    id: 'mock_004',
    text: 'Skincare routine for acne-prone skin #skincare #acne #beauty #routine',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 4,
    authorMeta: {
      id: 'user_004',
      name: 'skincarejen',
      nickName: 'Jen Skincare',
      verified: false,
      signature: 'Esthetician | Clear skin is possible!',
      avatar: 'https://placehold.co/150x150/FFB6C1/white?text=JS',
      following: 190,
      fans: 420000,
      heart: 15000000,
      video: 234,
      digg: 8500,
    },
    musicMeta: {
      musicId: 'music_004',
      musicName: 'Chill Vibes',
      musicAuthor: 'Lo-Fi',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 35,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 48,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 78000,
      shareCount: 15000,
      commentCount: 9200,
      playCount: 1800000,
      collectCount: 35000,
    },
    hashtags: [
      { id: 'h1', name: 'skincare' },
      { id: 'h2', name: 'acne' },
      { id: 'h3', name: 'beauty' },
      { id: 'h4', name: 'routine' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@skincarejen/video/mock_004',
  },
  // Tech Influencers
  {
    id: 'mock_005',
    text: 'Best tech gadgets of 2025 you NEED! #tech #gadgets #technology #review #techreview',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 1,
    authorMeta: {
      id: 'user_005',
      name: 'techwithtom',
      nickName: 'Tom Tech',
      verified: true,
      signature: 'Tech reviewer | Honest opinions | New videos daily | sponsors@techwithtom.io',
      avatar: 'https://placehold.co/150x150/5D5FEF/white?text=TT',
      following: 520,
      fans: 2100000,
      heart: 67000000,
      video: 489,
      digg: 15000,
    },
    musicMeta: {
      musicId: 'music_005',
      musicName: 'Tech Beats',
      musicAuthor: 'Digital',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 50,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 90,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 185000,
      shareCount: 28000,
      commentCount: 12000,
      playCount: 4200000,
      collectCount: 55000,
    },
    hashtags: [
      { id: 'h1', name: 'tech' },
      { id: 'h2', name: 'gadgets' },
      { id: 'h3', name: 'technology' },
      { id: 'h4', name: 'review' },
      { id: 'h5', name: 'techreview' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@techwithtom/video/mock_005',
  },
  {
    id: 'mock_006',
    text: 'iPhone vs Android in 2025 - which is better? #iphone #android #tech #comparison',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 6,
    authorMeta: {
      id: 'user_006',
      name: 'gadgetgirl',
      nickName: 'Amy Gadgets',
      verified: false,
      signature: 'Tech enthusiast | Smartphone comparisons',
      avatar: 'https://placehold.co/150x150/9B5DE5/white?text=AG',
      following: 340,
      fans: 156000,
      heart: 4500000,
      video: 178,
      digg: 4200,
    },
    musicMeta: {
      musicId: 'music_006',
      musicName: 'Future Sound',
      musicAuthor: 'Synth',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 45,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 75,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 32000,
      shareCount: 5500,
      commentCount: 4800,
      playCount: 720000,
      collectCount: 9500,
    },
    hashtags: [
      { id: 'h1', name: 'iphone' },
      { id: 'h2', name: 'android' },
      { id: 'h3', name: 'tech' },
      { id: 'h4', name: 'comparison' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@gadgetgirl/video/mock_006',
  },
  // Food Influencers
  {
    id: 'mock_007',
    text: '5-minute dinner recipes that actually taste good! #food #cooking #recipe #dinner #quickmeals',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 2,
    authorMeta: {
      id: 'user_007',
      name: 'chefcarlos',
      nickName: 'Chef Carlos',
      verified: true,
      signature: 'Professional chef | Easy recipes for everyone | booking@chefcarlos.com',
      avatar: 'https://placehold.co/150x150/F4A261/white?text=CC',
      following: 180,
      fans: 4500000,
      heart: 120000000,
      video: 678,
      digg: 25000,
    },
    musicMeta: {
      musicId: 'music_007',
      musicName: 'Kitchen Jam',
      musicAuthor: 'Cooking Channel',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 40,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 58,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 680000,
      shareCount: 95000,
      commentCount: 32000,
      playCount: 12000000,
      collectCount: 180000,
    },
    hashtags: [
      { id: 'h1', name: 'food' },
      { id: 'h2', name: 'cooking' },
      { id: 'h3', name: 'recipe' },
      { id: 'h4', name: 'dinner' },
      { id: 'h5', name: 'quickmeals' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@chefcarlos/video/mock_007',
  },
  {
    id: 'mock_008',
    text: 'Healthy meal prep for the week! #mealprep #healthy #food #nutrition #fitness',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 3,
    authorMeta: {
      id: 'user_008',
      name: 'healthyeats_lisa',
      nickName: 'Lisa Healthy Eats',
      verified: false,
      signature: 'Nutritionist | Meal prep queen | Healthy living',
      avatar: 'https://placehold.co/150x150/2A9D8F/white?text=LH',
      following: 290,
      fans: 380000,
      heart: 9800000,
      video: 245,
      digg: 6800,
    },
    musicMeta: {
      musicId: 'music_008',
      musicName: 'Chill Cooking',
      musicAuthor: 'Kitchen Vibes',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 35,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 65,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 52000,
      shareCount: 18000,
      commentCount: 5500,
      playCount: 1100000,
      collectCount: 42000,
    },
    hashtags: [
      { id: 'h1', name: 'mealprep' },
      { id: 'h2', name: 'healthy' },
      { id: 'h3', name: 'food' },
      { id: 'h4', name: 'nutrition' },
      { id: 'h5', name: 'fitness' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@healthyeats_lisa/video/mock_008',
  },
  // Fashion Influencers
  {
    id: 'mock_009',
    text: 'Fall outfit ideas 2025 #fashion #ootd #style #fall #outfitideas',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 1,
    authorMeta: {
      id: 'user_009',
      name: 'fashionista_maya',
      nickName: 'Maya Style',
      verified: true,
      signature: 'Fashion blogger | Sustainable style | Daily outfits | mgmt@mayastyle.fashion',
      avatar: 'https://placehold.co/150x150/E76F51/white?text=MS',
      following: 420,
      fans: 1800000,
      heart: 52000000,
      video: 412,
      digg: 11000,
    },
    musicMeta: {
      musicId: 'music_009',
      musicName: 'Runway Walk',
      musicAuthor: 'Fashion Beats',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 30,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 42,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 245000,
      shareCount: 18000,
      commentCount: 9500,
      playCount: 5800000,
      collectCount: 62000,
    },
    hashtags: [
      { id: 'h1', name: 'fashion' },
      { id: 'h2', name: 'ootd' },
      { id: 'h3', name: 'style' },
      { id: 'h4', name: 'fall' },
      { id: 'h5', name: 'outfitideas' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@fashionista_maya/video/mock_009',
  },
  {
    id: 'mock_010',
    text: 'Thrift haul - found so many gems! #thrift #fashion #sustainable #haul',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 4,
    authorMeta: {
      id: 'user_010',
      name: 'thriftqueen_alex',
      nickName: 'Alex Thrift',
      verified: false,
      signature: 'Thrift enthusiast | Budget fashion tips',
      avatar: 'https://placehold.co/150x150/264653/white?text=AT',
      following: 560,
      fans: 95000,
      heart: 2800000,
      video: 189,
      digg: 3500,
    },
    musicMeta: {
      musicId: 'music_010',
      musicName: 'Thrift Shop Beat',
      musicAuthor: 'Indie',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 45,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 78,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 38000,
      shareCount: 8200,
      commentCount: 4100,
      playCount: 680000,
      collectCount: 15000,
    },
    hashtags: [
      { id: 'h1', name: 'thrift' },
      { id: 'h2', name: 'fashion' },
      { id: 'h3', name: 'sustainable' },
      { id: 'h4', name: 'haul' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@thriftqueen_alex/video/mock_010',
  },
  // Travel Influencers
  {
    id: 'mock_011',
    text: 'Hidden gems in Bali you must visit! #travel #bali #wanderlust #explore #vacation',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 5,
    authorMeta: {
      id: 'user_011',
      name: 'travelwithjake',
      nickName: 'Jake Travels',
      verified: true,
      signature: 'Full-time traveler | 50+ countries | Adventure awaits | partner@jaketravels.com',
      avatar: 'https://placehold.co/150x150/00B4D8/white?text=JT',
      following: 380,
      fans: 2800000,
      heart: 78000000,
      video: 534,
      digg: 18000,
    },
    musicMeta: {
      musicId: 'music_011',
      musicName: 'Wanderlust',
      musicAuthor: 'Travel Vibes',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 55,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 85,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 420000,
      shareCount: 65000,
      commentCount: 18000,
      playCount: 8500000,
      collectCount: 120000,
    },
    hashtags: [
      { id: 'h1', name: 'travel' },
      { id: 'h2', name: 'bali' },
      { id: 'h3', name: 'wanderlust' },
      { id: 'h4', name: 'explore' },
      { id: 'h5', name: 'vacation' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@travelwithjake/video/mock_011',
  },
  {
    id: 'mock_012',
    text: 'Budget travel tips - Europe for under $50/day #budgettravel #europe #travel #tips',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 7,
    authorMeta: {
      id: 'user_012',
      name: 'budgettraveler_sam',
      nickName: 'Sam Budget Travel',
      verified: false,
      signature: 'Proving luxury travel on a budget is possible',
      avatar: 'https://placehold.co/150x150/0077B6/white?text=SB',
      following: 210,
      fans: 320000,
      heart: 8500000,
      video: 167,
      digg: 5200,
    },
    musicMeta: {
      musicId: 'music_012',
      musicName: 'Adventure Time',
      musicAuthor: 'Explorer',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 40,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 95,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 58000,
      shareCount: 22000,
      commentCount: 6800,
      playCount: 1400000,
      collectCount: 48000,
    },
    hashtags: [
      { id: 'h1', name: 'budgettravel' },
      { id: 'h2', name: 'europe' },
      { id: 'h3', name: 'travel' },
      { id: 'h4', name: 'tips' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@budgettraveler_sam/video/mock_012',
  },
  // Gaming Influencers
  {
    id: 'mock_013',
    text: 'Insane clutch in Valorant! #gaming #valorant #esports #gamer #clutch',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 1,
    authorMeta: {
      id: 'user_013',
      name: 'progamer_nina',
      nickName: 'Nina Pro Gamer',
      verified: true,
      signature: 'Pro Valorant player | Streaming daily | Esports',
      avatar: 'https://placehold.co/150x150/7209B7/white?text=NP',
      following: 890,
      fans: 1650000,
      heart: 48000000,
      video: 423,
      digg: 9500,
    },
    musicMeta: {
      musicId: 'music_013',
      musicName: 'Gaming Hype',
      musicAuthor: 'EDM Gamer',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 25,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 35,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 195000,
      shareCount: 28000,
      commentCount: 15000,
      playCount: 4200000,
      collectCount: 35000,
    },
    hashtags: [
      { id: 'h1', name: 'gaming' },
      { id: 'h2', name: 'valorant' },
      { id: 'h3', name: 'esports' },
      { id: 'h4', name: 'gamer' },
      { id: 'h5', name: 'clutch' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@progamer_nina/video/mock_013',
  },
  {
    id: 'mock_014',
    text: 'Minecraft building tips for beginners #minecraft #gaming #tutorial #build',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 3,
    authorMeta: {
      id: 'user_014',
      name: 'blockbuilder_dan',
      nickName: 'Dan Builds',
      verified: false,
      signature: 'Minecraft builder | Tutorials | Building community',
      avatar: 'https://placehold.co/150x150/560BAD/white?text=DB',
      following: 430,
      fans: 580000,
      heart: 16000000,
      video: 287,
      digg: 7200,
    },
    musicMeta: {
      musicId: 'music_014',
      musicName: 'Block Music',
      musicAuthor: 'Game OST',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 50,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 120,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 72000,
      shareCount: 12000,
      commentCount: 5400,
      playCount: 1600000,
      collectCount: 28000,
    },
    hashtags: [
      { id: 'h1', name: 'minecraft' },
      { id: 'h2', name: 'gaming' },
      { id: 'h3', name: 'tutorial' },
      { id: 'h4', name: 'build' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@blockbuilder_dan/video/mock_014',
  },
  // Comedy Influencers
  {
    id: 'mock_015',
    text: 'When your mom calls you by your full name #comedy #funny #relatable #mom #skit',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 2,
    authorMeta: {
      id: 'user_015',
      name: 'funnykim',
      nickName: 'Kim Comedy',
      verified: true,
      signature: 'Making you laugh daily | Comedian | Actor | agent@kimcomedy.com',
      avatar: 'https://placehold.co/150x150/F72585/white?text=KC',
      following: 650,
      fans: 5200000,
      heart: 185000000,
      video: 756,
      digg: 32000,
    },
    musicMeta: {
      musicId: 'music_015',
      musicName: 'Comedy Sound',
      musicAuthor: 'Funny Effects',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 20,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 28,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 850000,
      shareCount: 120000,
      commentCount: 45000,
      playCount: 18000000,
      collectCount: 95000,
    },
    hashtags: [
      { id: 'h1', name: 'comedy' },
      { id: 'h2', name: 'funny' },
      { id: 'h3', name: 'relatable' },
      { id: 'h4', name: 'mom' },
      { id: 'h5', name: 'skit' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@funnykim/video/mock_015',
  },
  // Education Influencers
  {
    id: 'mock_016',
    text: 'Study tips that got me into Harvard #education #study #tips #college #harvard',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 4,
    authorMeta: {
      id: 'user_016',
      name: 'studywithrachel',
      nickName: 'Rachel Study',
      verified: false,
      signature: 'Harvard student | Study tips | Making education fun',
      avatar: 'https://placehold.co/150x150/3A86FF/white?text=RS',
      following: 180,
      fans: 890000,
      heart: 28000000,
      video: 198,
      digg: 8900,
    },
    musicMeta: {
      musicId: 'music_016',
      musicName: 'Focus Music',
      musicAuthor: 'Study Beats',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 35,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 65,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 125000,
      shareCount: 48000,
      commentCount: 12000,
      playCount: 3200000,
      collectCount: 85000,
    },
    hashtags: [
      { id: 'h1', name: 'education' },
      { id: 'h2', name: 'study' },
      { id: 'h3', name: 'tips' },
      { id: 'h4', name: 'college' },
      { id: 'h5', name: 'harvard' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@studywithrachel/video/mock_016',
  },
  // Nano influencers (high engagement, small following)
  {
    id: 'mock_017',
    text: 'My small business journey - week 1! #smallbusiness #entrepreneur #business #startup',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 2,
    authorMeta: {
      id: 'user_017',
      name: 'startupstory_emma',
      nickName: 'Emma Startup',
      verified: false,
      signature: 'Building my dream business | Join my journey',
      avatar: 'https://placehold.co/150x150/06D6A0/white?text=ES',
      following: 420,
      fans: 8500,
      heart: 320000,
      video: 45,
      digg: 1200,
    },
    musicMeta: {
      musicId: 'music_017',
      musicName: 'Motivation',
      musicAuthor: 'Hustle',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 40,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 55,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 2800,
      shareCount: 850,
      commentCount: 420,
      playCount: 42000,
      collectCount: 1500,
    },
    hashtags: [
      { id: 'h1', name: 'smallbusiness' },
      { id: 'h2', name: 'entrepreneur' },
      { id: 'h3', name: 'business' },
      { id: 'h4', name: 'startup' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@startupstory_emma/video/mock_017',
  },
  {
    id: 'mock_018',
    text: 'Daily plant care routine #plants #plantcare #houseplants #plantmom',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 3,
    authorMeta: {
      id: 'user_018',
      name: 'plantlover_sofia',
      nickName: 'Sofia Plants',
      verified: false,
      signature: 'Plant mom | 100+ plants | Tips & tricks',
      avatar: 'https://placehold.co/150x150/52B788/white?text=SP',
      following: 340,
      fans: 12000,
      heart: 480000,
      video: 67,
      digg: 1800,
    },
    musicMeta: {
      musicId: 'music_018',
      musicName: 'Nature Sounds',
      musicAuthor: 'Ambient',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 30,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 45,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 3500,
      shareCount: 620,
      commentCount: 380,
      playCount: 58000,
      collectCount: 2200,
    },
    hashtags: [
      { id: 'h1', name: 'plants' },
      { id: 'h2', name: 'plantcare' },
      { id: 'h3', name: 'houseplants' },
      { id: 'h4', name: 'plantmom' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@plantlover_sofia/video/mock_018',
  },
  // Pet Influencers
  {
    id: 'mock_019',
    text: 'My golden retriever reacts to different foods! #dogs #pets #goldenretriever #funny #dogsoftiktok',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 1,
    authorMeta: {
      id: 'user_019',
      name: 'goldenmax_adventures',
      nickName: 'Max the Golden',
      verified: true,
      signature: 'Max the happiest dog | Daily adventures | Dogs are life | collabs@goldenmax.pet',
      avatar: 'https://placehold.co/150x150/FFD166/white?text=MG',
      following: 280,
      fans: 3800000,
      heart: 110000000,
      video: 456,
      digg: 22000,
    },
    musicMeta: {
      musicId: 'music_019',
      musicName: 'Happy Dog',
      musicAuthor: 'Pet Sounds',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 25,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 38,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 580000,
      shareCount: 85000,
      commentCount: 28000,
      playCount: 12500000,
      collectCount: 120000,
    },
    hashtags: [
      { id: 'h1', name: 'dogs' },
      { id: 'h2', name: 'pets' },
      { id: 'h3', name: 'goldenretriever' },
      { id: 'h4', name: 'funny' },
      { id: 'h5', name: 'dogsoftiktok' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@goldenmax_adventures/video/mock_019',
  },
  // Finance Influencers
  {
    id: 'mock_020',
    text: 'How I saved $10,000 in 6 months #finance #money #savings #budget #personalfinance',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 5,
    authorMeta: {
      id: 'user_020',
      name: 'moneywithmark',
      nickName: 'Mark Finance',
      verified: false,
      signature: 'Financial advisor | Making money simple | No BS finance',
      avatar: 'https://placehold.co/150x150/118AB2/white?text=MF',
      following: 150,
      fans: 720000,
      heart: 21000000,
      video: 234,
      digg: 6800,
    },
    musicMeta: {
      musicId: 'music_020',
      musicName: 'Money Talk',
      musicAuthor: 'Finance Beats',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 45,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 75,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 95000,
      shareCount: 35000,
      commentCount: 8500,
      playCount: 2100000,
      collectCount: 65000,
    },
    hashtags: [
      { id: 'h1', name: 'finance' },
      { id: 'h2', name: 'money' },
      { id: 'h3', name: 'savings' },
      { id: 'h4', name: 'budget' },
      { id: 'h5', name: 'personalfinance' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@moneywithmark/video/mock_020',
  },
  // Lifestyle Influencers
  {
    id: 'mock_021',
    text: 'Morning routine that changed my productivity #lifestyle #morning #routine #productivity #grwm',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 2,
    authorMeta: {
      id: 'user_021',
      name: 'lifestyle_olivia',
      nickName: 'Olivia Lifestyle',
      verified: true,
      signature: 'Living my best life | Lifestyle tips | Self-improvement',
      avatar: 'https://placehold.co/150x150/EF476F/white?text=OL',
      following: 490,
      fans: 1450000,
      heart: 42000000,
      video: 378,
      digg: 10500,
    },
    musicMeta: {
      musicId: 'music_021',
      musicName: 'Good Vibes',
      musicAuthor: 'Chill',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 35,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 52,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 185000,
      shareCount: 22000,
      commentCount: 9800,
      playCount: 4500000,
      collectCount: 55000,
    },
    hashtags: [
      { id: 'h1', name: 'lifestyle' },
      { id: 'h2', name: 'morning' },
      { id: 'h3', name: 'routine' },
      { id: 'h4', name: 'productivity' },
      { id: 'h5', name: 'grwm' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@lifestyle_olivia/video/mock_021',
  },
  // DIY Influencers
  {
    id: 'mock_022',
    text: 'DIY room transformation under $100! #diy #homedecor #roomtransformation #budget #home',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 4,
    authorMeta: {
      id: 'user_022',
      name: 'diyqueen_hannah',
      nickName: 'Hannah DIY',
      verified: false,
      signature: 'DIY enthusiast | Home transformation on a budget',
      avatar: 'https://placehold.co/150x150/F4A261/white?text=HD',
      following: 310,
      fans: 650000,
      heart: 18500000,
      video: 212,
      digg: 5600,
    },
    musicMeta: {
      musicId: 'music_022',
      musicName: 'Craft Time',
      musicAuthor: 'DIY Music',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 50,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 95,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 82000,
      shareCount: 28000,
      commentCount: 6200,
      playCount: 1850000,
      collectCount: 48000,
    },
    hashtags: [
      { id: 'h1', name: 'diy' },
      { id: 'h2', name: 'homedecor' },
      { id: 'h3', name: 'roomtransformation' },
      { id: 'h4', name: 'budget' },
      { id: 'h5', name: 'home' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@diyqueen_hannah/video/mock_022',
  },
  // Music Influencers
  {
    id: 'mock_023',
    text: 'Cover of the latest hit song! #music #singing #cover #singer #musician',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 3,
    authorMeta: {
      id: 'user_023',
      name: 'singer_marcus',
      nickName: 'Marcus Sings',
      verified: true,
      signature: 'Singer & Songwriter | Original music coming soon | press@marcussings.com',
      avatar: 'https://placehold.co/150x150/8338EC/white?text=MS',
      following: 420,
      fans: 2400000,
      heart: 68000000,
      video: 345,
      digg: 14000,
    },
    musicMeta: {
      musicId: 'music_023',
      musicName: 'Original Cover',
      musicAuthor: 'Marcus',
      musicOriginal: true,
      playUrl: '',
      coverThumb: '',
      duration: 60,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 65,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 320000,
      shareCount: 45000,
      commentCount: 18000,
      playCount: 7200000,
      collectCount: 85000,
    },
    hashtags: [
      { id: 'h1', name: 'music' },
      { id: 'h2', name: 'singing' },
      { id: 'h3', name: 'cover' },
      { id: 'h4', name: 'singer' },
      { id: 'h5', name: 'musician' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@singer_marcus/video/mock_023',
  },
  // Art Influencers
  {
    id: 'mock_024',
    text: 'Painting tutorial - sunset landscape #art #painting #artist #tutorial #creative',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 6,
    authorMeta: {
      id: 'user_024',
      name: 'artby_claire',
      nickName: 'Claire Art',
      verified: false,
      signature: 'Professional artist | Tutorials & tips | Commission open',
      avatar: 'https://placehold.co/150x150/FB5607/white?text=CA',
      following: 280,
      fans: 480000,
      heart: 14000000,
      video: 189,
      digg: 4800,
    },
    musicMeta: {
      musicId: 'music_024',
      musicName: 'Artistic Flow',
      musicAuthor: 'Creative',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 40,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 85,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 65000,
      shareCount: 12000,
      commentCount: 4500,
      playCount: 1400000,
      collectCount: 38000,
    },
    hashtags: [
      { id: 'h1', name: 'art' },
      { id: 'h2', name: 'painting' },
      { id: 'h3', name: 'artist' },
      { id: 'h4', name: 'tutorial' },
      { id: 'h5', name: 'creative' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@artby_claire/video/mock_024',
  },
  // Health/Wellness Influencers
  {
    id: 'mock_025',
    text: 'Mental health tips that actually work #mentalhealth #wellness #health #selfcare #tips',
    createTime: Math.floor(Date.now() / 1000) - 86400 * 2,
    authorMeta: {
      id: 'user_025',
      name: 'wellness_dr_amy',
      nickName: 'Dr. Amy Wellness',
      verified: true,
      signature: 'Licensed therapist | Mental health advocate | Here to help | inquiries@dramywellness.com',
      avatar: 'https://placehold.co/150x150/06D6A0/white?text=DA',
      following: 120,
      fans: 950000,
      heart: 32000000,
      video: 267,
      digg: 8200,
    },
    musicMeta: {
      musicId: 'music_025',
      musicName: 'Calm Mind',
      musicAuthor: 'Meditation',
      musicOriginal: false,
      playUrl: '',
      coverThumb: '',
      duration: 35,
    },
    videoMeta: {
      width: 1080,
      height: 1920,
      duration: 72,
      ratio: '9:16',
      coverUrl: '',
      dynamicCoverUrl: '',
    },
    stats: {
      diggCount: 145000,
      shareCount: 52000,
      commentCount: 12000,
      playCount: 3500000,
      collectCount: 95000,
    },
    hashtags: [
      { id: 'h1', name: 'mentalhealth' },
      { id: 'h2', name: 'wellness' },
      { id: 'h3', name: 'health' },
      { id: 'h4', name: 'selfcare' },
      { id: 'h5', name: 'tips' },
    ],
    mentions: [],
    webVideoUrl: 'https://tiktok.com/@wellness_dr_amy/video/mock_025',
  },
]

/**
 * Mock TikTok profile data
 */
export const mockTikTokProfiles: TikTokProfile[] = mockTikTokVideos.map((video) => ({
  id: video.authorMeta.id,
  uniqueId: video.authorMeta.name,
  nickname: video.authorMeta.nickName,
  signature: video.authorMeta.signature,
  avatar: video.authorMeta.avatar,
  verified: video.authorMeta.verified,
  secUid: `sec_${video.authorMeta.id}`,
  privateAccount: false,
  stats: {
    followingCount: video.authorMeta.following,
    followerCount: video.authorMeta.fans,
    heartCount: video.authorMeta.heart,
    videoCount: video.authorMeta.video,
    diggCount: video.authorMeta.digg,
  },
  recentVideos: [video],
}))

/**
 * Get mock discovery results filtered by hashtags
 */
export function getMockDiscoveryResults(hashtags: string[]): TikTokVideo[] {
  const normalizedHashtags = hashtags.map((h) => h.toLowerCase().replace('#', ''))

  // Filter videos that have at least one matching hashtag
  const matchingVideos = mockTikTokVideos.filter((video) => {
    const videoHashtags = video.hashtags.map((h) => h.name.toLowerCase())
    return normalizedHashtags.some((h) => videoHashtags.includes(h))
  })

  // If no matches, return a random subset for demo purposes
  if (matchingVideos.length === 0) {
    return mockTikTokVideos.slice(0, 10)
  }

  return matchingVideos
}

/**
 * Get mock profile results for specific usernames
 */
export function getMockProfileResults(usernames: string[]): TikTokProfile[] {
  const normalizedUsernames = usernames.map((u) =>
    u.toLowerCase().replace('@', '').replace('https://www.tiktok.com/@', '')
  )

  const matchingProfiles = mockTikTokProfiles.filter((profile) =>
    normalizedUsernames.includes(profile.uniqueId.toLowerCase())
  )

  // If no matches, return some random profiles for demo
  if (matchingProfiles.length === 0) {
    return mockTikTokProfiles.slice(0, Math.min(5, usernames.length))
  }

  return matchingProfiles
}

/**
 * Get all mock data for testing
 */
export function getAllMockData() {
  return {
    videos: mockTikTokVideos,
    profiles: mockTikTokProfiles,
    videoCount: mockTikTokVideos.length,
    profileCount: mockTikTokProfiles.length,
    niches: Array.from(new Set(mockTikTokVideos.flatMap((v) => v.hashtags.map((h) => h.name)))),
  }
}
