/**
 * Johnny5 Code Generator Service
 *
 * Generates code based on task descriptions using a Codex-like pattern.
 * Implements safety checks and template-based generation for common patterns.
 *
 * Key Features:
 * - Template-based generation for common patterns
 * - Safety validation before generation
 * - Supports React/TypeScript, CSS, and API routes
 * - Integrates with Proactive Builder for PR creation
 */

import { PROACTIVE_BUILDER_RULES } from './proactive-builder';

// ================================================================================
// Types
// ================================================================================

export interface CodeGenerationRequest {
  taskId: string;
  title: string;
  description: string;
  targetFiles: string[];
  language: 'typescript' | 'javascript' | 'css' | 'json';
  template?: CodeTemplate;
  context?: {
    existingCode?: string;
    relatedFiles?: string[];
    requirements?: string[];
  };
}

export interface CodeGenerationResult {
  success: boolean;
  files: GeneratedFile[];
  error?: string;
  tokensUsed: number;
  reasoning: string;
}

export interface GeneratedFile {
  path: string;
  content: string;
  linesAdded: number;
  linesRemoved: number;
  isNew: boolean;
}

export type CodeTemplate =
  | 'react-component'
  | 'react-hook'
  | 'api-route'
  | 'utility-function'
  | 'test-file'
  | 'css-module';

// ================================================================================
// Code Templates
// ================================================================================

const CODE_TEMPLATES: Record<CodeTemplate, string> = {
  'react-component': `'use client';

import React from 'react';

interface {{ComponentName}}Props {
  className?: string;
  // TODO: Add props based on requirements
}

/**
 * {{ComponentName}}
 *
 * {{description}}
 *
 * Generated by Johnny5 Code Generator
 */
export default function {{ComponentName}}({ className }: {{ComponentName}}Props) {
  return (
    <div className={\`\${className || ''}\`}>
      {/* TODO: Implement component */}
      <p>{{ComponentName}} component</p>
    </div>
  );
}
`,

  'react-hook': `import { useState, useEffect, useCallback } from 'react';

interface Use{{HookName}}Options {
  // TODO: Add options based on requirements
}

interface Use{{HookName}}Return {
  // TODO: Add return type based on requirements
  loading: boolean;
  error: string | null;
}

/**
 * use{{HookName}}
 *
 * {{description}}
 *
 * Generated by Johnny5 Code Generator
 */
export function use{{HookName}}(options: Use{{HookName}}Options = {}): Use{{HookName}}Return {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // TODO: Implement hook logic
  }, []);

  return {
    loading,
    error,
  };
}

export default use{{HookName}};
`,

  'api-route': `import { NextResponse } from 'next/server';

/**
 * {{description}}
 *
 * Generated by Johnny5 Code Generator
 */

export async function GET(request: Request) {
  try {
    // TODO: Implement GET handler
    const data = {
      success: true,
      message: '{{routeName}} endpoint',
    };

    return NextResponse.json(data);
  } catch (error) {
    console.error('{{routeName}} GET error:', error);
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json();

    // TODO: Implement POST handler
    const data = {
      success: true,
      message: '{{routeName}} created',
      data: body,
    };

    return NextResponse.json(data, { status: 201 });
  } catch (error) {
    console.error('{{routeName}} POST error:', error);
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    );
  }
}
`,

  'utility-function': `/**
 * {{functionName}}
 *
 * {{description}}
 *
 * Generated by Johnny5 Code Generator
 */

export interface {{FunctionName}}Options {
  // TODO: Add options based on requirements
}

export interface {{FunctionName}}Result {
  success: boolean;
  data?: unknown;
  error?: string;
}

export function {{functionName}}(
  input: unknown,
  options: {{FunctionName}}Options = {}
): {{FunctionName}}Result {
  try {
    // TODO: Implement function logic
    return {
      success: true,
      data: input,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

export default {{functionName}};
`,

  'test-file': `import { describe, it, expect, beforeEach, afterEach } from 'vitest';

/**
 * Tests for {{targetName}}
 *
 * Generated by Johnny5 Code Generator
 */

describe('{{targetName}}', () => {
  beforeEach(() => {
    // Setup before each test
  });

  afterEach(() => {
    // Cleanup after each test
  });

  it('should exist', () => {
    // TODO: Implement actual test
    expect(true).toBe(true);
  });

  it('should handle basic case', () => {
    // TODO: Add test case
    expect(true).toBe(true);
  });

  it('should handle edge cases', () => {
    // TODO: Add edge case tests
    expect(true).toBe(true);
  });

  it('should handle errors gracefully', () => {
    // TODO: Add error handling tests
    expect(true).toBe(true);
  });
});
`,

  'css-module': `/**
 * {{moduleName}} Styles
 *
 * {{description}}
 *
 * Generated by Johnny5 Code Generator
 */

.container {
  /* Base container styles */
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.header {
  /* Header section styles */
}

.content {
  /* Main content styles */
}

.footer {
  /* Footer section styles */
}

/* Responsive breakpoints */
@media (max-width: 768px) {
  .container {
    padding: 0.5rem;
  }
}

/* Dark mode support */
@media (prefers-color-scheme: dark) {
  .container {
    /* Dark mode overrides */
  }
}
`,
};

// ================================================================================
// Code Generator Service
// ================================================================================

class CodeGeneratorService {
  /**
   * Validate a generation request for safety
   */
  validateRequest(request: CodeGenerationRequest): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    // Check file count limit
    if (request.targetFiles.length > PROACTIVE_BUILDER_RULES.maxFilesPerPR) {
      errors.push(`Too many target files (max: ${PROACTIVE_BUILDER_RULES.maxFilesPerPR})`);
    }

    // Check for forbidden file patterns
    const forbiddenPatterns = ['.env', 'secrets', 'credentials', 'password'];
    for (const file of request.targetFiles) {
      if (forbiddenPatterns.some((pattern) => file.toLowerCase().includes(pattern))) {
        errors.push(`Cannot generate code for sensitive file: ${file}`);
      }
    }

    // Check for protected directories
    const protectedDirs = ['node_modules', '.git', 'dist', 'build'];
    for (const file of request.targetFiles) {
      if (protectedDirs.some((dir) => file.includes(`/${dir}/`))) {
        errors.push(`Cannot modify protected directory: ${file}`);
      }
    }

    return {
      valid: errors.length === 0,
      errors,
    };
  }

  /**
   * Generate code based on the request
   */
  async generateCode(request: CodeGenerationRequest): Promise<CodeGenerationResult> {
    // Validate request first
    const validation = this.validateRequest(request);
    if (!validation.valid) {
      return {
        success: false,
        files: [],
        error: validation.errors.join('; '),
        tokensUsed: 0,
        reasoning: 'Request failed validation checks',
      };
    }

    try {
      const files: GeneratedFile[] = [];

      for (const targetFile of request.targetFiles) {
        const generatedFile = await this.generateFileContent(targetFile, request);
        files.push(generatedFile);
      }

      const totalLines = files.reduce((sum, f) => sum + f.linesAdded, 0);

      // Check lines changed limit
      if (totalLines > PROACTIVE_BUILDER_RULES.maxLinesChanged) {
        return {
          success: false,
          files: [],
          error: `Generated too many lines (${totalLines}/${PROACTIVE_BUILDER_RULES.maxLinesChanged})`,
          tokensUsed: 0,
          reasoning: 'Generation exceeded line limit',
        };
      }

      return {
        success: true,
        files,
        tokensUsed: Math.floor(Math.random() * 5000) + 1000, // Mock token count
        reasoning: `Successfully generated ${files.length} files with ${totalLines} lines`,
      };
    } catch (error) {
      return {
        success: false,
        files: [],
        error: error instanceof Error ? error.message : 'Unknown error',
        tokensUsed: 0,
        reasoning: 'Generation failed with exception',
      };
    }
  }

  /**
   * Generate content for a single file
   */
  private async generateFileContent(
    filePath: string,
    request: CodeGenerationRequest
  ): Promise<GeneratedFile> {
    // Determine template based on file path
    const template = this.inferTemplate(filePath, request.template);
    const templateContent = CODE_TEMPLATES[template] || CODE_TEMPLATES['utility-function'];

    // Extract naming from file path
    const fileName = filePath.split('/').pop() || 'Component';
    const baseName = fileName.replace(/\.(tsx?|jsx?|css)$/, '');
    const componentName = this.toPascalCase(baseName);
    const functionName = this.toCamelCase(baseName);

    // Apply template variables
    let content = templateContent
      .replace(/\{\{ComponentName\}\}/g, componentName)
      .replace(/\{\{HookName\}\}/g, componentName.replace(/^use/, ''))
      .replace(/\{\{FunctionName\}\}/g, componentName)
      .replace(/\{\{functionName\}\}/g, functionName)
      .replace(/\{\{routeName\}\}/g, functionName)
      .replace(/\{\{targetName\}\}/g, componentName)
      .replace(/\{\{moduleName\}\}/g, componentName)
      .replace(/\{\{description\}\}/g, request.description);

    const lines = content.split('\n').length;

    return {
      path: filePath,
      content,
      linesAdded: lines,
      linesRemoved: 0,
      isNew: true,
    };
  }

  /**
   * Infer template type from file path
   */
  private inferTemplate(filePath: string, explicit?: CodeTemplate): CodeTemplate {
    if (explicit) return explicit;

    const lowerPath = filePath.toLowerCase();

    if (lowerPath.includes('/api/') || lowerPath.includes('route.ts')) {
      return 'api-route';
    }
    if (lowerPath.includes('/hooks/') || lowerPath.includes('use')) {
      return 'react-hook';
    }
    if (lowerPath.includes('.test.') || lowerPath.includes('.spec.')) {
      return 'test-file';
    }
    if (lowerPath.endsWith('.css') || lowerPath.includes('.module.css')) {
      return 'css-module';
    }
    if (lowerPath.includes('/lib/') || lowerPath.includes('/utils/')) {
      return 'utility-function';
    }

    return 'react-component';
  }

  /**
   * Convert string to PascalCase
   */
  private toPascalCase(str: string): string {
    return str
      .split(/[-_\s]/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }

  /**
   * Convert string to camelCase
   */
  private toCamelCase(str: string): string {
    const pascal = this.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }

  /**
   * Get available templates
   */
  getAvailableTemplates(): CodeTemplate[] {
    return Object.keys(CODE_TEMPLATES) as CodeTemplate[];
  }

  /**
   * Preview a template with sample values
   */
  previewTemplate(template: CodeTemplate, description: string = 'Sample description'): string {
    const templateContent = CODE_TEMPLATES[template];
    if (!templateContent) return 'Template not found';

    return templateContent
      .replace(/\{\{ComponentName\}\}/g, 'SampleComponent')
      .replace(/\{\{HookName\}\}/g, 'SampleHook')
      .replace(/\{\{FunctionName\}\}/g, 'SampleFunction')
      .replace(/\{\{functionName\}\}/g, 'sampleFunction')
      .replace(/\{\{routeName\}\}/g, 'sampleRoute')
      .replace(/\{\{targetName\}\}/g, 'SampleTarget')
      .replace(/\{\{moduleName\}\}/g, 'SampleModule')
      .replace(/\{\{description\}\}/g, description);
  }
}

// ================================================================================
// Export Singleton Instance
// ================================================================================

export const codeGenerator = new CodeGeneratorService();
export default codeGenerator;
